# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc --mtriple=loongarch64 -run-pass=legalizer %s -o - \
# RUN: | FileCheck %s
---
name:            const_i8
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: const_i8
    ; CHECK: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 -127
    ; CHECK-NEXT: $r4 = COPY [[C]](s64)
    ; CHECK-NEXT: PseudoRET implicit $r4
    %0:_(s8) = G_CONSTANT i8 129
    %1:_(s64) = G_ANYEXT %0(s8)
    $r4 = COPY %1(s64)
    PseudoRET implicit $r4

...
---
name:            const_i15
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: const_i15
    ; CHECK: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 15
    ; CHECK-NEXT: $r4 = COPY [[C]](s64)
    ; CHECK-NEXT: PseudoRET implicit $r4
    %0:_(s15) = G_CONSTANT i15 15
    %1:_(s64) = G_ANYEXT %0(s15)
    $r4 = COPY %1(s64)
    PseudoRET implicit $r4

...
---
name:            const_i16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: const_i16
    ; CHECK: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 767
    ; CHECK-NEXT: $r4 = COPY [[C]](s64)
    ; CHECK-NEXT: PseudoRET implicit $r4
    %0:_(s16) = G_CONSTANT i16 -64769
    %1:_(s64) = G_ANYEXT %0(s16)
    $r4 = COPY %1(s64)
    PseudoRET implicit $r4

...
---
name:            const_i32
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: const_i32
    ; CHECK: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 -64769
    ; CHECK-NEXT: $r4 = COPY [[C]](s64)
    ; CHECK-NEXT: PseudoRET implicit $r4
    %0:_(s32) = G_CONSTANT i32 -64769
    %1:_(s64) = G_ANYEXT %0(s32)
    $r4 = COPY %1(s64)
    PseudoRET implicit $r4

...
---
name:            const_i64
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: const_i64
    ; CHECK: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 2147483649
    ; CHECK-NEXT: $r4 = COPY [[C]](s64)
    ; CHECK-NEXT: PseudoRET implicit $r4
    %0:_(s64) = G_CONSTANT i64 2147483649
    $r4 = COPY %0(s64)
    PseudoRET implicit $r4

...
---
name:            const_i72
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: const_i72
    ; CHECK: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 -2147483649312
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s64) = G_CONSTANT i64 -1
    ; CHECK-NEXT: $r4 = COPY [[C]](s64)
    ; CHECK-NEXT: $r5 = COPY [[C1]](s64)
    ; CHECK-NEXT: PseudoRET implicit $r4, implicit $r5
    %0:_(s72) = G_CONSTANT i72 -2147483649312
    %1:_(s128) = G_ANYEXT %0(s72)
    %2:_(s64), %3:_(s64) = G_UNMERGE_VALUES %1(s128)
    $r4 = COPY %2(s64)
    $r5 = COPY %3(s64)
    PseudoRET implicit $r4, implicit $r5

...
---
name:            const_i128
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: const_i128
    ; CHECK: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 21474831289
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
    ; CHECK-NEXT: $r4 = COPY [[C]](s64)
    ; CHECK-NEXT: $r5 = COPY [[C1]](s64)
    ; CHECK-NEXT: PseudoRET implicit $r4, implicit $r5
    %0:_(s128) = G_CONSTANT i128 21474831289
    %1:_(s64), %2:_(s64) = G_UNMERGE_VALUES %0(s128)
    $r4 = COPY %1(s64)
    $r5 = COPY %2(s64)
    PseudoRET implicit $r4, implicit $r5

...
---
name:            const_i192
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: const_i192
    ; CHECK: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 -214772364921
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s64) = G_CONSTANT i64 -1
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s64) = G_CONSTANT i64 -1
    ; CHECK-NEXT: $r4 = COPY [[C]](s64)
    ; CHECK-NEXT: $r5 = COPY [[C1]](s64)
    ; CHECK-NEXT: $r6 = COPY [[C2]](s64)
    ; CHECK-NEXT: PseudoRET implicit $r4, implicit $r5, implicit $r6
    %0:_(s192) = G_CONSTANT i192 -214772364921
    %1:_(s64), %2:_(s64), %3:_(s64) = G_UNMERGE_VALUES %0(s192)
    $r4 = COPY %1(s64)
    $r5 = COPY %2(s64)
    $r6 = COPY %3(s64)
    PseudoRET implicit $r4, implicit $r5, implicit $r6

...
---
name:            const_null
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: const_null
    ; CHECK: [[C:%[0-9]+]]:_(p0) = G_CONSTANT i64 0
    ; CHECK-NEXT: $r4 = COPY [[C]](p0)
    ; CHECK-NEXT: PseudoRET implicit $r4
    %0:_(p0) = G_CONSTANT i64 0
    $r4 = COPY %0(p0)
    PseudoRET implicit $r4

...
