# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc --mtriple=loongarch32 -run-pass=legalizer %s -o - \
# RUN: | FileCheck %s
---
name:            const_i7
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: const_i7
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK-NEXT: $r4 = COPY [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $r4
    %0:_(s7) = G_CONSTANT i7 15
    %1:_(s32) = G_ANYEXT %0(s7)
    $r4 = COPY %1(s32)
    PseudoRET implicit $r4

...
---
name:            const_i8
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: const_i8
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 -127
    ; CHECK-NEXT: $r4 = COPY [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $r4
    %0:_(s8) = G_CONSTANT i8 129
    %1:_(s32) = G_ANYEXT %0(s8)
    $r4 = COPY %1(s32)
    PseudoRET implicit $r4

...
---
name:            const_i16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: const_i16
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 32767
    ; CHECK-NEXT: $r4 = COPY [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $r4
    %0:_(s16) = G_CONSTANT i16 -32769
    %1:_(s32) = G_ANYEXT %0(s16)
    $r4 = COPY %1(s32)
    PseudoRET implicit $r4

...
---
name:            const_i32
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: const_i32
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 -2147483647
    ; CHECK-NEXT: $r4 = COPY [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $r4
    %0:_(s32) = G_CONSTANT i32 2147483649
    $r4 = COPY %0(s32)
    PseudoRET implicit $r4

...
---
name:            const_i48
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: const_i48
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: $r4 = COPY [[C]](s32)
    ; CHECK-NEXT: $r5 = COPY [[C1]](s32)
    ; CHECK-NEXT: PseudoRET implicit $r4, implicit $r5
    %0:_(s48) = G_CONSTANT i48 2
    %1:_(s64) = G_ANYEXT %0(s48)
    %2:_(s32), %3:_(s32) = G_UNMERGE_VALUES %1(s64)
    $r4 = COPY %2(s32)
    $r5 = COPY %3(s32)
    PseudoRET implicit $r4, implicit $r5

...
---
name:            const_i64
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: const_i64
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 -2147483647
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: $r4 = COPY [[C]](s32)
    ; CHECK-NEXT: $r5 = COPY [[C1]](s32)
    ; CHECK-NEXT: PseudoRET implicit $r4, implicit $r5
    %0:_(s64) = G_CONSTANT i64 2147483649
    %1:_(s32), %2:_(s32) = G_UNMERGE_VALUES %0(s64)
    $r4 = COPY %1(s32)
    $r5 = COPY %2(s32)
    PseudoRET implicit $r4, implicit $r5

...
---
name:            const_i96
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: const_i96
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 -121
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 -51
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 -1
    ; CHECK-NEXT: $r4 = COPY [[C]](s32)
    ; CHECK-NEXT: $r5 = COPY [[C1]](s32)
    ; CHECK-NEXT: $r6 = COPY [[C2]](s32)
    ; CHECK-NEXT: PseudoRET implicit $r4, implicit $r5, implicit $r6
    %0:_(s96) = G_CONSTANT i96 -214748364921
    %1:_(s32), %2:_(s32), %3:_(s32) = G_UNMERGE_VALUES %0(s96)
    $r4 = COPY %1(s32)
    $r5 = COPY %2(s32)
    $r6 = COPY %3(s32)
    PseudoRET implicit $r4, implicit $r5, implicit $r6

...
---
name:            const_null
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: const_null
    ; CHECK: [[C:%[0-9]+]]:_(p0) = G_CONSTANT i32 0
    ; CHECK-NEXT: $r4 = COPY [[C]](p0)
    ; CHECK-NEXT: PseudoRET implicit $r4
    %0:_(p0) = G_CONSTANT i32 0
    $r4 = COPY %0(p0)
    PseudoRET implicit $r4

...
