# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc --mtriple=loongarch32 -mattr=-ual -run-pass=legalizer %s -o - \
# RUN:   | FileCheck %s -check-prefix=NOUAL
# RUN: llc --mtriple=loongarch32 -mattr=+ual -run-pass=legalizer %s -o - \
# RUN:   | FileCheck %s -check-prefix=UAL

---
name:            load_i8
alignment:       32
tracksRegLiveness: true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
  - { id: 2, class: _ }
frameInfo:
  maxAlignment:    1
body:             |
  bb.1:
    liveins: $r4

    ; NOUAL-LABEL: name: load_i8
    ; NOUAL: liveins: $r4
    ; NOUAL-NEXT: {{  $}}
    ; NOUAL-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $r4
    ; NOUAL-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p0) :: (load (s8))
    ; NOUAL-NEXT: $r4 = COPY [[LOAD]](s32)
    ; NOUAL-NEXT: PseudoRET implicit $r4
    ;
    ; UAL-LABEL: name: load_i8
    ; UAL: liveins: $r4
    ; UAL-NEXT: {{  $}}
    ; UAL-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $r4
    ; UAL-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p0) :: (load (s8))
    ; UAL-NEXT: $r4 = COPY [[LOAD]](s32)
    ; UAL-NEXT: PseudoRET implicit $r4
    %0:_(p0) = COPY $r4
    %1:_(s8) = G_LOAD %0(p0) :: (load (s8))
    %2:_(s32) = G_ANYEXT %1(s8)
    $r4 = COPY %2(s32)
    PseudoRET implicit $r4

...
---
name:            load_i16
alignment:       32
tracksRegLiveness: true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
  - { id: 2, class: _ }
frameInfo:
  maxAlignment:    1
body:             |
  bb.1:
    liveins: $r4

    ; NOUAL-LABEL: name: load_i16
    ; NOUAL: liveins: $r4
    ; NOUAL-NEXT: {{  $}}
    ; NOUAL-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $r4
    ; NOUAL-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p0) :: (load (s16))
    ; NOUAL-NEXT: $r4 = COPY [[LOAD]](s32)
    ; NOUAL-NEXT: PseudoRET implicit $r4
    ;
    ; UAL-LABEL: name: load_i16
    ; UAL: liveins: $r4
    ; UAL-NEXT: {{  $}}
    ; UAL-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $r4
    ; UAL-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p0) :: (load (s16))
    ; UAL-NEXT: $r4 = COPY [[LOAD]](s32)
    ; UAL-NEXT: PseudoRET implicit $r4
    %0:_(p0) = COPY $r4
    %1:_(s16) = G_LOAD %0(p0) :: (load (s16))
    %2:_(s32) = G_ANYEXT %1(s16)
    $r4 = COPY %2(s32)
    PseudoRET implicit $r4

...
---
name:            load_i32
alignment:       32
tracksRegLiveness: true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
frameInfo:
  maxAlignment:    1
body:             |
  bb.1:
    liveins: $r4

    ; NOUAL-LABEL: name: load_i32
    ; NOUAL: liveins: $r4
    ; NOUAL-NEXT: {{  $}}
    ; NOUAL-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $r4
    ; NOUAL-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p0) :: (load (s32))
    ; NOUAL-NEXT: $r4 = COPY [[LOAD]](s32)
    ; NOUAL-NEXT: PseudoRET implicit $r4
    ;
    ; UAL-LABEL: name: load_i32
    ; UAL: liveins: $r4
    ; UAL-NEXT: {{  $}}
    ; UAL-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $r4
    ; UAL-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p0) :: (load (s32))
    ; UAL-NEXT: $r4 = COPY [[LOAD]](s32)
    ; UAL-NEXT: PseudoRET implicit $r4
    %0:_(p0) = COPY $r4
    %1:_(s32) = G_LOAD %0(p0) :: (load (s32))
    $r4 = COPY %1(s32)
    PseudoRET implicit $r4

...
---
name:            load_i64
alignment:       32
tracksRegLiveness: true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
  - { id: 2, class: _ }
  - { id: 3, class: _ }
frameInfo:
  maxAlignment:    1
body:             |
  bb.1:
    liveins: $r4

    ; NOUAL-LABEL: name: load_i64
    ; NOUAL: liveins: $r4
    ; NOUAL-NEXT: {{  $}}
    ; NOUAL-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $r4
    ; NOUAL-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p0) :: (load (s32), align 8)
    ; NOUAL-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; NOUAL-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s32)
    ; NOUAL-NEXT: [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD]](p0) :: (load (s32) from unknown-address + 4)
    ; NOUAL-NEXT: $r4 = COPY [[LOAD]](s32)
    ; NOUAL-NEXT: $r5 = COPY [[LOAD1]](s32)
    ; NOUAL-NEXT: PseudoRET implicit $r4, implicit $r5
    ;
    ; UAL-LABEL: name: load_i64
    ; UAL: liveins: $r4
    ; UAL-NEXT: {{  $}}
    ; UAL-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $r4
    ; UAL-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p0) :: (load (s32), align 8)
    ; UAL-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; UAL-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s32)
    ; UAL-NEXT: [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD]](p0) :: (load (s32) from unknown-address + 4)
    ; UAL-NEXT: $r4 = COPY [[LOAD]](s32)
    ; UAL-NEXT: $r5 = COPY [[LOAD1]](s32)
    ; UAL-NEXT: PseudoRET implicit $r4, implicit $r5
    %0:_(p0) = COPY $r4
    %1:_(s64) = G_LOAD %0(p0) :: (load (s64))
    %2:_(s32), %3:_(s32) = G_UNMERGE_VALUES %1(s64)
    $r4 = COPY %2(s32)
    $r5 = COPY %3(s32)
    PseudoRET implicit $r4, implicit $r5

...
---
name:            load_ptr
alignment:       32
tracksRegLiveness: true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
frameInfo:
  maxAlignment:    1
body:             |
  bb.1:
    liveins: $r4

    ; NOUAL-LABEL: name: load_ptr
    ; NOUAL: liveins: $r4
    ; NOUAL-NEXT: {{  $}}
    ; NOUAL-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $r4
    ; NOUAL-NEXT: [[LOAD:%[0-9]+]]:_(p0) = G_LOAD [[COPY]](p0) :: (load (p0), align 8)
    ; NOUAL-NEXT: $r4 = COPY [[LOAD]](p0)
    ; NOUAL-NEXT: PseudoRET implicit $r4
    ;
    ; UAL-LABEL: name: load_ptr
    ; UAL: liveins: $r4
    ; UAL-NEXT: {{  $}}
    ; UAL-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $r4
    ; UAL-NEXT: [[LOAD:%[0-9]+]]:_(p0) = G_LOAD [[COPY]](p0) :: (load (p0), align 8)
    ; UAL-NEXT: $r4 = COPY [[LOAD]](p0)
    ; UAL-NEXT: PseudoRET implicit $r4
    %0:_(p0) = COPY $r4
    %1:_(p0) = G_LOAD %0(p0) :: (load (p0), align 8)
    $r4 = COPY %1(p0)
    PseudoRET implicit $r4

...
---
name:            load_i16_unaligned
alignment:       32
tracksRegLiveness: true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
  - { id: 2, class: _ }
frameInfo:
  maxAlignment:    1
body:             |
  bb.1:
    liveins: $r4

    ; NOUAL-LABEL: name: load_i16_unaligned
    ; NOUAL: liveins: $r4
    ; NOUAL-NEXT: {{  $}}
    ; NOUAL-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $r4
    ; NOUAL-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[COPY]](p0) :: (load (s8))
    ; NOUAL-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; NOUAL-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s32)
    ; NOUAL-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD]](p0) :: (load (s8) from unknown-address + 1)
    ; NOUAL-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; NOUAL-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[LOAD]], [[C1]](s32)
    ; NOUAL-NEXT: [[OR:%[0-9]+]]:_(s32) = G_OR [[SHL]], [[ZEXTLOAD]]
    ; NOUAL-NEXT: $r4 = COPY [[OR]](s32)
    ; NOUAL-NEXT: PseudoRET implicit $r4
    ;
    ; UAL-LABEL: name: load_i16_unaligned
    ; UAL: liveins: $r4
    ; UAL-NEXT: {{  $}}
    ; UAL-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $r4
    ; UAL-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p0) :: (load (s16), align 1)
    ; UAL-NEXT: $r4 = COPY [[LOAD]](s32)
    ; UAL-NEXT: PseudoRET implicit $r4
    %0:_(p0) = COPY $r4
    %1:_(s16) = G_LOAD %0(p0) :: (load (s16), align 1)
    %2:_(s32) = G_ANYEXT %1(s16)
    $r4 = COPY %2(s32)
    PseudoRET implicit $r4

...
---
name:            load_i32_unaligned
alignment:       32
tracksRegLiveness: true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
frameInfo:
  maxAlignment:    1
body:             |
  bb.1:
    liveins: $r4

    ; NOUAL-LABEL: name: load_i32_unaligned
    ; NOUAL: liveins: $r4
    ; NOUAL-NEXT: {{  $}}
    ; NOUAL-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $r4
    ; NOUAL-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[COPY]](p0) :: (load (s8))
    ; NOUAL-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; NOUAL-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s32)
    ; NOUAL-NEXT: [[ZEXTLOAD1:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD]](p0) :: (load (s8) from unknown-address + 1)
    ; NOUAL-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; NOUAL-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[ZEXTLOAD1]], [[C1]](s32)
    ; NOUAL-NEXT: [[OR:%[0-9]+]]:_(s32) = G_OR [[SHL]], [[ZEXTLOAD]]
    ; NOUAL-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; NOUAL-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s32)
    ; NOUAL-NEXT: [[ZEXTLOAD2:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD1]](p0) :: (load (s8) from unknown-address + 2)
    ; NOUAL-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; NOUAL-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD1]], [[C3]](s32)
    ; NOUAL-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD2]](p0) :: (load (s8) from unknown-address + 3)
    ; NOUAL-NEXT: [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; NOUAL-NEXT: [[SHL1:%[0-9]+]]:_(s32) = G_SHL [[LOAD]], [[C4]](s32)
    ; NOUAL-NEXT: [[OR1:%[0-9]+]]:_(s32) = G_OR [[SHL1]], [[ZEXTLOAD2]]
    ; NOUAL-NEXT: [[C5:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; NOUAL-NEXT: [[SHL2:%[0-9]+]]:_(s32) = G_SHL [[OR1]], [[C5]](s32)
    ; NOUAL-NEXT: [[OR2:%[0-9]+]]:_(s32) = G_OR [[SHL2]], [[OR]]
    ; NOUAL-NEXT: $r4 = COPY [[OR2]](s32)
    ; NOUAL-NEXT: PseudoRET implicit $r4
    ;
    ; UAL-LABEL: name: load_i32_unaligned
    ; UAL: liveins: $r4
    ; UAL-NEXT: {{  $}}
    ; UAL-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $r4
    ; UAL-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p0) :: (load (s32), align 1)
    ; UAL-NEXT: $r4 = COPY [[LOAD]](s32)
    ; UAL-NEXT: PseudoRET implicit $r4
    %0:_(p0) = COPY $r4
    %1:_(s32) = G_LOAD %0(p0) :: (load (s32), align 1)
    $r4 = COPY %1(s32)
    PseudoRET implicit $r4

...
---
name:            load_i32_align2
alignment:       32
tracksRegLiveness: true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
frameInfo:
  maxAlignment:    1
body:             |
  bb.1:
    liveins: $r4

    ; NOUAL-LABEL: name: load_i32_align2
    ; NOUAL: liveins: $r4
    ; NOUAL-NEXT: {{  $}}
    ; NOUAL-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $r4
    ; NOUAL-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[COPY]](p0) :: (load (s16))
    ; NOUAL-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; NOUAL-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s32)
    ; NOUAL-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD]](p0) :: (load (s16) from unknown-address + 2)
    ; NOUAL-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; NOUAL-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[LOAD]], [[C1]](s32)
    ; NOUAL-NEXT: [[OR:%[0-9]+]]:_(s32) = G_OR [[SHL]], [[ZEXTLOAD]]
    ; NOUAL-NEXT: $r4 = COPY [[OR]](s32)
    ; NOUAL-NEXT: PseudoRET implicit $r4
    ;
    ; UAL-LABEL: name: load_i32_align2
    ; UAL: liveins: $r4
    ; UAL-NEXT: {{  $}}
    ; UAL-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $r4
    ; UAL-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p0) :: (load (s32), align 2)
    ; UAL-NEXT: $r4 = COPY [[LOAD]](s32)
    ; UAL-NEXT: PseudoRET implicit $r4
    %0:_(p0) = COPY $r4
    %1:_(s32) = G_LOAD %0(p0) :: (load (s32), align 2)
    $r4 = COPY %1(s32)
    PseudoRET implicit $r4

...
---
name:            load_i64_unaligned
alignment:       32
tracksRegLiveness: true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
  - { id: 2, class: _ }
  - { id: 3, class: _ }
frameInfo:
  maxAlignment:    1
body:             |
  bb.1:
    liveins: $r4

    ; NOUAL-LABEL: name: load_i64_unaligned
    ; NOUAL: liveins: $r4
    ; NOUAL-NEXT: {{  $}}
    ; NOUAL-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $r4
    ; NOUAL-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[COPY]](p0) :: (load (s8))
    ; NOUAL-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; NOUAL-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s32)
    ; NOUAL-NEXT: [[ZEXTLOAD1:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD]](p0) :: (load (s8) from unknown-address + 1)
    ; NOUAL-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; NOUAL-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[ZEXTLOAD1]], [[C1]](s32)
    ; NOUAL-NEXT: [[OR:%[0-9]+]]:_(s32) = G_OR [[SHL]], [[ZEXTLOAD]]
    ; NOUAL-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; NOUAL-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s32)
    ; NOUAL-NEXT: [[ZEXTLOAD2:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD1]](p0) :: (load (s8) from unknown-address + 2)
    ; NOUAL-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; NOUAL-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD1]], [[C3]](s32)
    ; NOUAL-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD2]](p0) :: (load (s8) from unknown-address + 3)
    ; NOUAL-NEXT: [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; NOUAL-NEXT: [[SHL1:%[0-9]+]]:_(s32) = G_SHL [[LOAD]], [[C4]](s32)
    ; NOUAL-NEXT: [[OR1:%[0-9]+]]:_(s32) = G_OR [[SHL1]], [[ZEXTLOAD2]]
    ; NOUAL-NEXT: [[C5:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; NOUAL-NEXT: [[SHL2:%[0-9]+]]:_(s32) = G_SHL [[OR1]], [[C5]](s32)
    ; NOUAL-NEXT: [[OR2:%[0-9]+]]:_(s32) = G_OR [[SHL2]], [[OR]]
    ; NOUAL-NEXT: [[C6:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; NOUAL-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C6]](s32)
    ; NOUAL-NEXT: [[ZEXTLOAD3:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD3]](p0) :: (load (s8) from unknown-address + 4)
    ; NOUAL-NEXT: [[C7:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; NOUAL-NEXT: [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD3]], [[C7]](s32)
    ; NOUAL-NEXT: [[ZEXTLOAD4:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD4]](p0) :: (load (s8) from unknown-address + 5)
    ; NOUAL-NEXT: [[C8:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; NOUAL-NEXT: [[SHL3:%[0-9]+]]:_(s32) = G_SHL [[ZEXTLOAD4]], [[C8]](s32)
    ; NOUAL-NEXT: [[OR3:%[0-9]+]]:_(s32) = G_OR [[SHL3]], [[ZEXTLOAD3]]
    ; NOUAL-NEXT: [[C9:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; NOUAL-NEXT: [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD3]], [[C9]](s32)
    ; NOUAL-NEXT: [[ZEXTLOAD5:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD5]](p0) :: (load (s8) from unknown-address + 6)
    ; NOUAL-NEXT: [[C10:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; NOUAL-NEXT: [[PTR_ADD6:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD5]], [[C10]](s32)
    ; NOUAL-NEXT: [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD6]](p0) :: (load (s8) from unknown-address + 7)
    ; NOUAL-NEXT: [[C11:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; NOUAL-NEXT: [[SHL4:%[0-9]+]]:_(s32) = G_SHL [[LOAD1]], [[C11]](s32)
    ; NOUAL-NEXT: [[OR4:%[0-9]+]]:_(s32) = G_OR [[SHL4]], [[ZEXTLOAD5]]
    ; NOUAL-NEXT: [[C12:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; NOUAL-NEXT: [[SHL5:%[0-9]+]]:_(s32) = G_SHL [[OR4]], [[C12]](s32)
    ; NOUAL-NEXT: [[OR5:%[0-9]+]]:_(s32) = G_OR [[SHL5]], [[OR3]]
    ; NOUAL-NEXT: $r4 = COPY [[OR2]](s32)
    ; NOUAL-NEXT: $r5 = COPY [[OR5]](s32)
    ; NOUAL-NEXT: PseudoRET implicit $r4, implicit $r5
    ;
    ; UAL-LABEL: name: load_i64_unaligned
    ; UAL: liveins: $r4
    ; UAL-NEXT: {{  $}}
    ; UAL-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $r4
    ; UAL-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p0) :: (load (s32), align 1)
    ; UAL-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; UAL-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s32)
    ; UAL-NEXT: [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD]](p0) :: (load (s32) from unknown-address + 4, align 1)
    ; UAL-NEXT: $r4 = COPY [[LOAD]](s32)
    ; UAL-NEXT: $r5 = COPY [[LOAD1]](s32)
    ; UAL-NEXT: PseudoRET implicit $r4, implicit $r5
    %0:_(p0) = COPY $r4
    %1:_(s64) = G_LOAD %0(p0) :: (load (s64), align 1)
    %2:_(s32), %3:_(s32) = G_UNMERGE_VALUES %1(s64)
    $r4 = COPY %2(s32)
    $r5 = COPY %3(s32)
    PseudoRET implicit $r4, implicit $r5

...
