# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc --mtriple=loongarch64 -run-pass=legalizer %s -o - \
# RUN: | FileCheck %s
---
name:            shl_i8
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: shl_i8
    ; CHECK: [[COPY:%[0-9]+]]:_(s64) = COPY $r4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $r5
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 255
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s64) = G_AND [[COPY1]], [[C]]
    ; CHECK-NEXT: [[SHL:%[0-9]+]]:_(s64) = G_SHL [[COPY]], [[AND]](s64)
    ; CHECK-NEXT: $r4 = COPY [[SHL]](s64)
    ; CHECK-NEXT: PseudoRET implicit $r4
    %0:_(s64) = COPY $r4
    %1:_(s64) = COPY $r5
    %2:_(s8) = G_TRUNC %0(s64)
    %3:_(s8) = G_TRUNC %1(s64)
    %4:_(s8) = G_SHL %2, %3
    %5:_(s64) = G_ANYEXT %4(s8)
    $r4 = COPY %5(s64)
    PseudoRET implicit $r4

...
---
name:            shl_i15
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: shl_i15
    ; CHECK: [[COPY:%[0-9]+]]:_(s64) = COPY $r4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $r5
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 32767
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s64) = G_AND [[COPY1]], [[C]]
    ; CHECK-NEXT: [[SHL:%[0-9]+]]:_(s64) = G_SHL [[COPY]], [[AND]](s64)
    ; CHECK-NEXT: $r4 = COPY [[SHL]](s64)
    ; CHECK-NEXT: PseudoRET implicit $r4
    %0:_(s64) = COPY $r4
    %1:_(s64) = COPY $r5
    %2:_(s15) = G_TRUNC %0(s64)
    %3:_(s15) = G_TRUNC %1(s64)
    %4:_(s15) = G_SHL %2, %3
    %5:_(s64) = G_ANYEXT %4(s15)
    $r4 = COPY %5(s64)
    PseudoRET implicit $r4

...
---
name:            shl_i16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: shl_i16
    ; CHECK: [[COPY:%[0-9]+]]:_(s64) = COPY $r4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $r5
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 65535
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s64) = G_AND [[COPY1]], [[C]]
    ; CHECK-NEXT: [[SHL:%[0-9]+]]:_(s64) = G_SHL [[COPY]], [[AND]](s64)
    ; CHECK-NEXT: $r4 = COPY [[SHL]](s64)
    ; CHECK-NEXT: PseudoRET implicit $r4
    %0:_(s64) = COPY $r4
    %1:_(s64) = COPY $r5
    %2:_(s16) = G_TRUNC %0(s64)
    %3:_(s16) = G_TRUNC %1(s64)
    %4:_(s16) = G_SHL %2, %3
    %5:_(s64) = G_ANYEXT %4(s16)
    $r4 = COPY %5(s64)
    PseudoRET implicit $r4

...
---
name:            shl_i32
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: shl_i32
    ; CHECK: [[COPY:%[0-9]+]]:_(s64) = COPY $r4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $r5
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 4294967295
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s64) = G_AND [[COPY1]], [[C]]
    ; CHECK-NEXT: [[SHL:%[0-9]+]]:_(s64) = G_SHL [[COPY]], [[AND]](s64)
    ; CHECK-NEXT: $r4 = COPY [[SHL]](s64)
    ; CHECK-NEXT: PseudoRET implicit $r4
    %0:_(s64) = COPY $r4
    %1:_(s64) = COPY $r5
    %2:_(s32) = G_TRUNC %0(s64)
    %3:_(s32) = G_TRUNC %1(s64)
    %4:_(s32) = G_SHL %2, %3
    %5:_(s64) = G_ANYEXT %4(s32)
    $r4 = COPY %5(s64)
    PseudoRET implicit $r4

...
---
name:            shl_i64
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: shl_i64
    ; CHECK: [[COPY:%[0-9]+]]:_(s64) = COPY $r4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $r5
    ; CHECK-NEXT: [[SHL:%[0-9]+]]:_(s64) = G_SHL [[COPY]], [[COPY1]](s64)
    ; CHECK-NEXT: $r4 = COPY [[SHL]](s64)
    ; CHECK-NEXT: PseudoRET implicit $r4
    %0:_(s64) = COPY $r4
    %1:_(s64) = COPY $r5
    %2:_(s64) = G_SHL %0, %1
    $r4 = COPY %2(s64)
    PseudoRET implicit $r4

...
---
name:            shl_i72
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: shl_i72
    ; CHECK: %x00:_(s64) = COPY $r4
    ; CHECK-NEXT: %x01:_(s64) = COPY $r5
    ; CHECK-NEXT: %y00:_(s64) = COPY $r6
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 64
    ; CHECK-NEXT: [[SUB:%[0-9]+]]:_(s64) = G_SUB %y00, [[C]]
    ; CHECK-NEXT: [[SUB1:%[0-9]+]]:_(s64) = G_SUB [[C]], %y00
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:_(s64) = G_ICMP intpred(ult), %y00(s64), [[C]]
    ; CHECK-NEXT: [[ICMP1:%[0-9]+]]:_(s64) = G_ICMP intpred(eq), %y00(s64), [[C1]]
    ; CHECK-NEXT: [[SHL:%[0-9]+]]:_(s64) = G_SHL %x00, %y00(s64)
    ; CHECK-NEXT: [[LSHR:%[0-9]+]]:_(s64) = G_LSHR %x00, [[SUB1]](s64)
    ; CHECK-NEXT: [[SHL1:%[0-9]+]]:_(s64) = G_SHL %x01, %y00(s64)
    ; CHECK-NEXT: [[OR:%[0-9]+]]:_(s64) = G_OR [[LSHR]], [[SHL1]]
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
    ; CHECK-NEXT: [[SHL2:%[0-9]+]]:_(s64) = G_SHL %x00, [[SUB]](s64)
    ; CHECK-NEXT: [[SELECT:%[0-9]+]]:_(s64) = G_SELECT [[ICMP]](s64), [[SHL]], [[C2]]
    ; CHECK-NEXT: [[SELECT1:%[0-9]+]]:_(s64) = G_SELECT [[ICMP]](s64), [[OR]], [[SHL2]]
    ; CHECK-NEXT: [[SELECT2:%[0-9]+]]:_(s64) = G_SELECT [[ICMP1]](s64), %x01, [[SELECT1]]
    ; CHECK-NEXT: $r4 = COPY [[SELECT]](s64)
    ; CHECK-NEXT: $r5 = COPY [[SELECT2]](s64)
    ; CHECK-NEXT: PseudoRET implicit $r4, implicit $r5
    %x00:_(s64) = COPY $r4
    %x01:_(s64) = COPY $r5
    %y00:_(s64) = COPY $r6
    %y01:_(s64) = COPY $r7
    %x0:_(s128) = G_MERGE_VALUES %x00(s64), %x01
    %y0:_(s128) = G_MERGE_VALUES %y00(s64), %y01
    %x:_(s72) = G_TRUNC %x0(s128)
    %y:_(s72) = G_TRUNC %y0(s128)
    %z:_(s72) = G_SHL %x, %y
    %z0:_(s128) = G_ANYEXT %z(s72)
    %z00:_(s64), %z01:_(s64) = G_UNMERGE_VALUES %z0(s128)
    $r4 = COPY %z00(s64)
    $r5 = COPY %z01(s64)
    PseudoRET implicit $r4, implicit $r5

...
---
name:            shl_i128
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: shl_i128
    ; CHECK: %lo1:_(s64) = COPY $r4
    ; CHECK-NEXT: %hi1:_(s64) = COPY $r5
    ; CHECK-NEXT: %lo2:_(s64) = COPY $r6
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 64
    ; CHECK-NEXT: [[SUB:%[0-9]+]]:_(s64) = G_SUB %lo2, [[C]]
    ; CHECK-NEXT: [[SUB1:%[0-9]+]]:_(s64) = G_SUB [[C]], %lo2
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:_(s64) = G_ICMP intpred(ult), %lo2(s64), [[C]]
    ; CHECK-NEXT: [[ICMP1:%[0-9]+]]:_(s64) = G_ICMP intpred(eq), %lo2(s64), [[C1]]
    ; CHECK-NEXT: [[SHL:%[0-9]+]]:_(s64) = G_SHL %lo1, %lo2(s64)
    ; CHECK-NEXT: [[LSHR:%[0-9]+]]:_(s64) = G_LSHR %lo1, [[SUB1]](s64)
    ; CHECK-NEXT: [[SHL1:%[0-9]+]]:_(s64) = G_SHL %hi1, %lo2(s64)
    ; CHECK-NEXT: [[OR:%[0-9]+]]:_(s64) = G_OR [[LSHR]], [[SHL1]]
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
    ; CHECK-NEXT: [[SHL2:%[0-9]+]]:_(s64) = G_SHL %lo1, [[SUB]](s64)
    ; CHECK-NEXT: [[SELECT:%[0-9]+]]:_(s64) = G_SELECT [[ICMP]](s64), [[SHL]], [[C2]]
    ; CHECK-NEXT: [[SELECT1:%[0-9]+]]:_(s64) = G_SELECT [[ICMP]](s64), [[OR]], [[SHL2]]
    ; CHECK-NEXT: [[SELECT2:%[0-9]+]]:_(s64) = G_SELECT [[ICMP1]](s64), %hi1, [[SELECT1]]
    ; CHECK-NEXT: $r4 = COPY [[SELECT]](s64)
    ; CHECK-NEXT: $r5 = COPY [[SELECT2]](s64)
    ; CHECK-NEXT: PseudoRET implicit $r4, implicit $r5
    %lo1:_(s64) = COPY $r4
    %hi1:_(s64) = COPY $r5
    %lo2:_(s64) = COPY $r6
    %hi2:_(s64) = COPY $r7
    %x1:_(s128) = G_MERGE_VALUES %lo1(s64), %hi1(s64)
    %x2:_(s128) = G_MERGE_VALUES %lo2(s64), %hi2(s64)
    %y:_(s128) = G_SHL %x1, %x2
    %loy:_(s64), %hiy:_(s64) = G_UNMERGE_VALUES %y(s128)
    $r4 = COPY %loy(s64)
    $r5 = COPY %hiy(s64)
    PseudoRET implicit $r4, implicit $r5

...
---
name:            shl_i192
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: shl_i192
    ; CHECK: %lo1:_(s64) = COPY $r4
    ; CHECK-NEXT: %mid1:_(s64) = COPY $r5
    ; CHECK-NEXT: %hi1:_(s64) = COPY $r6
    ; CHECK-NEXT: %lo2:_(s64) = COPY $r7
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 128
    ; CHECK-NEXT: [[SUB:%[0-9]+]]:_(s64) = G_SUB %lo2, [[C]]
    ; CHECK-NEXT: [[SUB1:%[0-9]+]]:_(s64) = G_SUB [[C]], %lo2
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:_(s64) = G_ICMP intpred(ult), %lo2(s64), [[C]]
    ; CHECK-NEXT: [[ICMP1:%[0-9]+]]:_(s64) = G_ICMP intpred(eq), %lo2(s64), [[C1]]
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s64) = G_CONSTANT i64 64
    ; CHECK-NEXT: [[SUB2:%[0-9]+]]:_(s64) = G_SUB %lo2, [[C2]]
    ; CHECK-NEXT: [[SUB3:%[0-9]+]]:_(s64) = G_SUB [[C2]], %lo2
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
    ; CHECK-NEXT: [[ICMP2:%[0-9]+]]:_(s64) = G_ICMP intpred(ult), %lo2(s64), [[C2]]
    ; CHECK-NEXT: [[ICMP3:%[0-9]+]]:_(s64) = G_ICMP intpred(eq), %lo2(s64), [[C3]]
    ; CHECK-NEXT: [[SHL:%[0-9]+]]:_(s64) = G_SHL %lo1, %lo2(s64)
    ; CHECK-NEXT: [[LSHR:%[0-9]+]]:_(s64) = G_LSHR %lo1, [[SUB3]](s64)
    ; CHECK-NEXT: [[SHL1:%[0-9]+]]:_(s64) = G_SHL %mid1, %lo2(s64)
    ; CHECK-NEXT: [[OR:%[0-9]+]]:_(s64) = G_OR [[LSHR]], [[SHL1]]
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
    ; CHECK-NEXT: [[SHL2:%[0-9]+]]:_(s64) = G_SHL %lo1, [[SUB2]](s64)
    ; CHECK-NEXT: [[SELECT:%[0-9]+]]:_(s64) = G_SELECT [[ICMP2]](s64), [[SHL]], [[C4]]
    ; CHECK-NEXT: [[SELECT1:%[0-9]+]]:_(s64) = G_SELECT [[ICMP2]](s64), [[OR]], [[SHL2]]
    ; CHECK-NEXT: [[SELECT2:%[0-9]+]]:_(s64) = G_SELECT [[ICMP3]](s64), %mid1, [[SELECT1]]
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s64) = G_CONSTANT i64 64
    ; CHECK-NEXT: [[SUB4:%[0-9]+]]:_(s64) = G_SUB [[SUB1]], [[C5]]
    ; CHECK-NEXT: [[SUB5:%[0-9]+]]:_(s64) = G_SUB [[C5]], [[SUB1]]
    ; CHECK-NEXT: [[C6:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
    ; CHECK-NEXT: [[ICMP4:%[0-9]+]]:_(s64) = G_ICMP intpred(ult), [[SUB1]](s64), [[C5]]
    ; CHECK-NEXT: [[ICMP5:%[0-9]+]]:_(s64) = G_ICMP intpred(eq), [[SUB1]](s64), [[C6]]
    ; CHECK-NEXT: [[LSHR1:%[0-9]+]]:_(s64) = G_LSHR %lo1, [[SUB1]](s64)
    ; CHECK-NEXT: [[SHL3:%[0-9]+]]:_(s64) = G_SHL %mid1, [[SUB5]](s64)
    ; CHECK-NEXT: [[OR1:%[0-9]+]]:_(s64) = G_OR [[LSHR1]], [[SHL3]]
    ; CHECK-NEXT: [[LSHR2:%[0-9]+]]:_(s64) = G_LSHR %mid1, [[SUB4]](s64)
    ; CHECK-NEXT: [[SELECT3:%[0-9]+]]:_(s64) = G_SELECT [[ICMP4]](s64), [[OR1]], [[LSHR2]]
    ; CHECK-NEXT: [[SELECT4:%[0-9]+]]:_(s64) = G_SELECT [[ICMP5]](s64), %lo1, [[SELECT3]]
    ; CHECK-NEXT: [[C7:%[0-9]+]]:_(s64) = G_CONSTANT i64 64
    ; CHECK-NEXT: [[ICMP6:%[0-9]+]]:_(s64) = G_ICMP intpred(ult), %lo2(s64), [[C7]]
    ; CHECK-NEXT: [[SHL4:%[0-9]+]]:_(s64) = G_SHL %hi1, %lo2(s64)
    ; CHECK-NEXT: [[C8:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
    ; CHECK-NEXT: [[SELECT5:%[0-9]+]]:_(s64) = G_SELECT [[ICMP6]](s64), [[SHL4]], [[C8]]
    ; CHECK-NEXT: [[OR2:%[0-9]+]]:_(s64) = G_OR [[SELECT4]], [[SELECT5]]
    ; CHECK-NEXT: [[C9:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
    ; CHECK-NEXT: [[C10:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
    ; CHECK-NEXT: [[C11:%[0-9]+]]:_(s64) = G_CONSTANT i64 64
    ; CHECK-NEXT: [[ICMP7:%[0-9]+]]:_(s64) = G_ICMP intpred(ult), [[SUB]](s64), [[C11]]
    ; CHECK-NEXT: [[SHL5:%[0-9]+]]:_(s64) = G_SHL %lo1, [[SUB]](s64)
    ; CHECK-NEXT: [[C12:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
    ; CHECK-NEXT: [[SELECT6:%[0-9]+]]:_(s64) = G_SELECT [[ICMP7]](s64), [[SHL5]], [[C12]]
    ; CHECK-NEXT: [[SELECT7:%[0-9]+]]:_(s64) = G_SELECT [[ICMP]](s64), [[SELECT]], [[C9]]
    ; CHECK-NEXT: [[SELECT8:%[0-9]+]]:_(s64) = G_SELECT [[ICMP]](s64), [[SELECT2]], [[C10]]
    ; CHECK-NEXT: [[SELECT9:%[0-9]+]]:_(s64) = G_SELECT [[ICMP]](s64), [[OR2]], [[SELECT6]]
    ; CHECK-NEXT: [[SELECT10:%[0-9]+]]:_(s64) = G_SELECT [[ICMP1]](s64), %hi1, [[SELECT9]]
    ; CHECK-NEXT: $r4 = COPY [[SELECT7]](s64)
    ; CHECK-NEXT: $r5 = COPY [[SELECT8]](s64)
    ; CHECK-NEXT: $r6 = COPY [[SELECT10]](s64)
    ; CHECK-NEXT: PseudoRET implicit $r4, implicit $r5, implicit $r6
    %lo1:_(s64) = COPY $r4
    %mid1:_(s64) = COPY $r5
    %hi1:_(s64) = COPY $r6
    %lo2:_(s64) = COPY $r7
    %mid2:_(s64) = COPY $r8
    %hi2:_(s64) = COPY $r9
    %x1:_(s192) = G_MERGE_VALUES %lo1(s64), %mid1(s64), %hi1(s64)
    %x2:_(s192) = G_MERGE_VALUES %lo2(s64), %mid2(s64), %hi2(s64)
    %y:_(s192) = G_SHL %x1, %x2
    %lo:_(s64), %mid:_(s64), %hi:_(s64) = G_UNMERGE_VALUES %y(s192)
    $r4 = COPY %lo(s64)
    $r5 = COPY %mid(s64)
    $r6 = COPY %hi(s64)
    PseudoRET implicit $r4, implicit $r5, implicit $r6

...
---
name:            shl_i48
body:             |
  bb.0:
    liveins: $r4, $r5

    ; CHECK-LABEL: name: shl_i48
    ; CHECK: liveins: $r4, $r5
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $r4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $r5
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 281474976710655
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s64) = G_AND [[COPY1]], [[C]]
    ; CHECK-NEXT: [[SHL:%[0-9]+]]:_(s64) = G_SHL [[COPY]], [[AND]](s64)
    ; CHECK-NEXT: $r4 = COPY [[SHL]](s64)
    ; CHECK-NEXT: PseudoRET implicit $r4
    %2:_(s64) = COPY $r4
    %0:_(s48) = G_TRUNC %2(s64)
    %3:_(s64) = COPY $r5
    %1:_(s48) = G_TRUNC %3(s64)
    %4:_(s48) = G_SHL %0, %1(s48)
    %5:_(s64) = G_ANYEXT %4(s48)
    $r4 = COPY %5(s64)
    PseudoRET implicit $r4

...
