# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc --mtriple=loongarch32 -mattr=-ual -run-pass=legalizer %s -o - \
# RUN:   | FileCheck %s -check-prefix=NOUAL
# RUN: llc --mtriple=loongarch32 -mattr=+ual -run-pass=legalizer %s -o - \
# RUN:   | FileCheck %s -check-prefix=UAL

---
name:            store_i8
alignment:       32
tracksRegLiveness: true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
  - { id: 2, class: _ }
frameInfo:
  maxAlignment:    1
body:             |
  bb.1:
    liveins: $r4, $r5

    ; NOUAL-LABEL: name: store_i8
    ; NOUAL: liveins: $r4, $r5
    ; NOUAL-NEXT: {{  $}}
    ; NOUAL-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r4
    ; NOUAL-NEXT: [[COPY1:%[0-9]+]]:_(p0) = COPY $r5
    ; NOUAL-NEXT: G_STORE [[COPY]](s32), [[COPY1]](p0) :: (store (s8))
    ; NOUAL-NEXT: PseudoRET
    ;
    ; UAL-LABEL: name: store_i8
    ; UAL: liveins: $r4, $r5
    ; UAL-NEXT: {{  $}}
    ; UAL-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r4
    ; UAL-NEXT: [[COPY1:%[0-9]+]]:_(p0) = COPY $r5
    ; UAL-NEXT: G_STORE [[COPY]](s32), [[COPY1]](p0) :: (store (s8))
    ; UAL-NEXT: PseudoRET
    %2:_(s32) = COPY $r4
    %0:_(s8) = G_TRUNC %2(s32)
    %1:_(p0) = COPY $r5
    G_STORE %0(s8), %1(p0) :: (store (s8))
    PseudoRET

...
---
name:            store_i16
alignment:       32
tracksRegLiveness: true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
  - { id: 2, class: _ }
frameInfo:
  maxAlignment:    1
body:             |
  bb.1:
    liveins: $r4, $r5

    ; NOUAL-LABEL: name: store_i16
    ; NOUAL: liveins: $r4, $r5
    ; NOUAL-NEXT: {{  $}}
    ; NOUAL-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r4
    ; NOUAL-NEXT: [[COPY1:%[0-9]+]]:_(p0) = COPY $r5
    ; NOUAL-NEXT: G_STORE [[COPY]](s32), [[COPY1]](p0) :: (store (s16))
    ; NOUAL-NEXT: PseudoRET
    ;
    ; UAL-LABEL: name: store_i16
    ; UAL: liveins: $r4, $r5
    ; UAL-NEXT: {{  $}}
    ; UAL-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r4
    ; UAL-NEXT: [[COPY1:%[0-9]+]]:_(p0) = COPY $r5
    ; UAL-NEXT: G_STORE [[COPY]](s32), [[COPY1]](p0) :: (store (s16))
    ; UAL-NEXT: PseudoRET
    %2:_(s32) = COPY $r4
    %0:_(s16) = G_TRUNC %2(s32)
    %1:_(p0) = COPY $r5
    G_STORE %0(s16), %1(p0) :: (store (s16))
    PseudoRET

...
---
name:            store_i32
alignment:       32
tracksRegLiveness: true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
frameInfo:
  maxAlignment:    1
body:             |
  bb.1:
    liveins: $r4, $r5

    ; NOUAL-LABEL: name: store_i32
    ; NOUAL: liveins: $r4, $r5
    ; NOUAL-NEXT: {{  $}}
    ; NOUAL-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r4
    ; NOUAL-NEXT: [[COPY1:%[0-9]+]]:_(p0) = COPY $r5
    ; NOUAL-NEXT: G_STORE [[COPY]](s32), [[COPY1]](p0) :: (store (s32))
    ; NOUAL-NEXT: PseudoRET
    ;
    ; UAL-LABEL: name: store_i32
    ; UAL: liveins: $r4, $r5
    ; UAL-NEXT: {{  $}}
    ; UAL-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r4
    ; UAL-NEXT: [[COPY1:%[0-9]+]]:_(p0) = COPY $r5
    ; UAL-NEXT: G_STORE [[COPY]](s32), [[COPY1]](p0) :: (store (s32))
    ; UAL-NEXT: PseudoRET
    %0:_(s32) = COPY $r4
    %1:_(p0) = COPY $r5
    G_STORE %0(s32), %1(p0) :: (store (s32))
    PseudoRET

...
---
name:            store_i64
alignment:       32
tracksRegLiveness: true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
  - { id: 2, class: _ }
  - { id: 3, class: _ }
frameInfo:
  maxAlignment:    1
body:             |
  bb.1:
    liveins: $r4, $r5, $r6

    ; NOUAL-LABEL: name: store_i64
    ; NOUAL: liveins: $r4, $r5, $r6
    ; NOUAL-NEXT: {{  $}}
    ; NOUAL-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r4
    ; NOUAL-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r5
    ; NOUAL-NEXT: [[COPY2:%[0-9]+]]:_(p0) = COPY $r6
    ; NOUAL-NEXT: G_STORE [[COPY]](s32), [[COPY2]](p0) :: (store (s32), align 8)
    ; NOUAL-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; NOUAL-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY2]], [[C]](s32)
    ; NOUAL-NEXT: G_STORE [[COPY1]](s32), [[PTR_ADD]](p0) :: (store (s32) into unknown-address + 4)
    ; NOUAL-NEXT: PseudoRET
    ;
    ; UAL-LABEL: name: store_i64
    ; UAL: liveins: $r4, $r5, $r6
    ; UAL-NEXT: {{  $}}
    ; UAL-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r4
    ; UAL-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r5
    ; UAL-NEXT: [[COPY2:%[0-9]+]]:_(p0) = COPY $r6
    ; UAL-NEXT: G_STORE [[COPY]](s32), [[COPY2]](p0) :: (store (s32), align 8)
    ; UAL-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; UAL-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY2]], [[C]](s32)
    ; UAL-NEXT: G_STORE [[COPY1]](s32), [[PTR_ADD]](p0) :: (store (s32) into unknown-address + 4)
    ; UAL-NEXT: PseudoRET
    %2:_(s32) = COPY $r4
    %3:_(s32) = COPY $r5
    %0:_(s64) = G_MERGE_VALUES %2(s32), %3(s32)
    %1:_(p0) = COPY $r6
    G_STORE %0(s64), %1(p0) :: (store (s64))
    PseudoRET

...
---
name:            store_ptr
alignment:       32
tracksRegLiveness: true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
frameInfo:
  maxAlignment:    1
body:             |
  bb.1:
    liveins: $r4, $r5

    ; NOUAL-LABEL: name: store_ptr
    ; NOUAL: liveins: $r4, $r5
    ; NOUAL-NEXT: {{  $}}
    ; NOUAL-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $r4
    ; NOUAL-NEXT: [[COPY1:%[0-9]+]]:_(p0) = COPY $r5
    ; NOUAL-NEXT: G_STORE [[COPY]](p0), [[COPY1]](p0) :: (store (p0), align 8)
    ; NOUAL-NEXT: PseudoRET
    ;
    ; UAL-LABEL: name: store_ptr
    ; UAL: liveins: $r4, $r5
    ; UAL-NEXT: {{  $}}
    ; UAL-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $r4
    ; UAL-NEXT: [[COPY1:%[0-9]+]]:_(p0) = COPY $r5
    ; UAL-NEXT: G_STORE [[COPY]](p0), [[COPY1]](p0) :: (store (p0), align 8)
    ; UAL-NEXT: PseudoRET
    %0:_(p0) = COPY $r4
    %1:_(p0) = COPY $r5
    G_STORE %0(p0), %1(p0) :: (store (p0), align 8)
    PseudoRET

...
---
name:            store_i16_unaligned
alignment:       32
tracksRegLiveness: true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
  - { id: 2, class: _ }
frameInfo:
  maxAlignment:    1
body:             |
  bb.1:
    liveins: $r4, $r5

    ; NOUAL-LABEL: name: store_i16_unaligned
    ; NOUAL: liveins: $r4, $r5
    ; NOUAL-NEXT: {{  $}}
    ; NOUAL-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r4
    ; NOUAL-NEXT: [[COPY1:%[0-9]+]]:_(p0) = COPY $r5
    ; NOUAL-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; NOUAL-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; NOUAL-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[COPY]], [[C1]]
    ; NOUAL-NEXT: [[LSHR:%[0-9]+]]:_(s32) = G_LSHR [[AND]], [[C]](s32)
    ; NOUAL-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; NOUAL-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY1]], [[C2]](s32)
    ; NOUAL-NEXT: G_STORE [[COPY]](s32), [[COPY1]](p0) :: (store (s8))
    ; NOUAL-NEXT: G_STORE [[LSHR]](s32), [[PTR_ADD]](p0) :: (store (s8) into unknown-address + 1)
    ; NOUAL-NEXT: PseudoRET
    ;
    ; UAL-LABEL: name: store_i16_unaligned
    ; UAL: liveins: $r4, $r5
    ; UAL-NEXT: {{  $}}
    ; UAL-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r4
    ; UAL-NEXT: [[COPY1:%[0-9]+]]:_(p0) = COPY $r5
    ; UAL-NEXT: G_STORE [[COPY]](s32), [[COPY1]](p0) :: (store (s16), align 1)
    ; UAL-NEXT: PseudoRET
    %2:_(s32) = COPY $r4
    %0:_(s16) = G_TRUNC %2(s32)
    %1:_(p0) = COPY $r5
    G_STORE %0(s16), %1(p0) :: (store (s16), align 1)
    PseudoRET

...
---
name:            store_i32_unaligned
alignment:       32
tracksRegLiveness: true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
frameInfo:
  maxAlignment:    1
body:             |
  bb.1:
    liveins: $r4, $r5

    ; NOUAL-LABEL: name: store_i32_unaligned
    ; NOUAL: liveins: $r4, $r5
    ; NOUAL-NEXT: {{  $}}
    ; NOUAL-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r4
    ; NOUAL-NEXT: [[COPY1:%[0-9]+]]:_(p0) = COPY $r5
    ; NOUAL-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY [[COPY]](s32)
    ; NOUAL-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; NOUAL-NEXT: [[LSHR:%[0-9]+]]:_(s32) = G_LSHR [[COPY2]], [[C]](s32)
    ; NOUAL-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; NOUAL-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY1]], [[C1]](s32)
    ; NOUAL-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; NOUAL-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; NOUAL-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[COPY2]], [[C3]]
    ; NOUAL-NEXT: [[LSHR1:%[0-9]+]]:_(s32) = G_LSHR [[AND]], [[C2]](s32)
    ; NOUAL-NEXT: [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; NOUAL-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY1]], [[C4]](s32)
    ; NOUAL-NEXT: G_STORE [[COPY2]](s32), [[COPY1]](p0) :: (store (s8))
    ; NOUAL-NEXT: G_STORE [[LSHR1]](s32), [[PTR_ADD1]](p0) :: (store (s8) into unknown-address + 1)
    ; NOUAL-NEXT: [[C5:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; NOUAL-NEXT: [[LSHR2:%[0-9]+]]:_(s32) = G_LSHR [[LSHR]], [[C5]](s32)
    ; NOUAL-NEXT: [[C6:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; NOUAL-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD]], [[C6]](s32)
    ; NOUAL-NEXT: G_STORE [[LSHR]](s32), [[PTR_ADD]](p0) :: (store (s8) into unknown-address + 2)
    ; NOUAL-NEXT: G_STORE [[LSHR2]](s32), [[PTR_ADD2]](p0) :: (store (s8) into unknown-address + 3)
    ; NOUAL-NEXT: PseudoRET
    ;
    ; UAL-LABEL: name: store_i32_unaligned
    ; UAL: liveins: $r4, $r5
    ; UAL-NEXT: {{  $}}
    ; UAL-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r4
    ; UAL-NEXT: [[COPY1:%[0-9]+]]:_(p0) = COPY $r5
    ; UAL-NEXT: G_STORE [[COPY]](s32), [[COPY1]](p0) :: (store (s32), align 1)
    ; UAL-NEXT: PseudoRET
    %0:_(s32) = COPY $r4
    %1:_(p0) = COPY $r5
    G_STORE %0(s32), %1(p0) :: (store (s32), align 1)
    PseudoRET

...
---
name:            store_i32_align2
alignment:       32
tracksRegLiveness: true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
frameInfo:
  maxAlignment:    1
body:             |
  bb.1:
    liveins: $r4, $r5

    ; NOUAL-LABEL: name: store_i32_align2
    ; NOUAL: liveins: $r4, $r5
    ; NOUAL-NEXT: {{  $}}
    ; NOUAL-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r4
    ; NOUAL-NEXT: [[COPY1:%[0-9]+]]:_(p0) = COPY $r5
    ; NOUAL-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY [[COPY]](s32)
    ; NOUAL-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; NOUAL-NEXT: [[LSHR:%[0-9]+]]:_(s32) = G_LSHR [[COPY2]], [[C]](s32)
    ; NOUAL-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; NOUAL-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY1]], [[C1]](s32)
    ; NOUAL-NEXT: G_STORE [[COPY2]](s32), [[COPY1]](p0) :: (store (s16))
    ; NOUAL-NEXT: G_STORE [[LSHR]](s32), [[PTR_ADD]](p0) :: (store (s16) into unknown-address + 2)
    ; NOUAL-NEXT: PseudoRET
    ;
    ; UAL-LABEL: name: store_i32_align2
    ; UAL: liveins: $r4, $r5
    ; UAL-NEXT: {{  $}}
    ; UAL-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r4
    ; UAL-NEXT: [[COPY1:%[0-9]+]]:_(p0) = COPY $r5
    ; UAL-NEXT: G_STORE [[COPY]](s32), [[COPY1]](p0) :: (store (s32), align 2)
    ; UAL-NEXT: PseudoRET
    %0:_(s32) = COPY $r4
    %1:_(p0) = COPY $r5
    G_STORE %0(s32), %1(p0) :: (store (s32), align 2)
    PseudoRET

...
