# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc --mtriple=loongarch64 -run-pass=legalizer %s -o - \
# RUN: | FileCheck %s

---
name:            uaddo_i8
body:             |
  bb.1:
    liveins: $r4, $r5

    ; CHECK-LABEL: name: uaddo_i8
    ; CHECK: liveins: $r4, $r5
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $r4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $r5
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:_(s64) = G_ADD [[COPY]], [[COPY1]]
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 255
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s64) = G_AND [[ADD]], [[C]]
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s64) = G_CONSTANT i64 255
    ; CHECK-NEXT: [[AND1:%[0-9]+]]:_(s64) = G_AND [[COPY1]], [[C1]]
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:_(s64) = G_ICMP intpred(ult), [[AND]](s64), [[AND1]]
    ; CHECK-NEXT: $r4 = COPY [[ADD]](s64)
    ; CHECK-NEXT: $r5 = COPY [[ICMP]](s64)
    ; CHECK-NEXT: PseudoRET implicit $r4, implicit $r5
    %2:_(s64) = COPY $r4
    %0:_(s8) = G_TRUNC %2(s64)
    %3:_(s64) = COPY $r5
    %1:_(s8) = G_TRUNC %3(s64)
    %4:_(s8), %5:_(s1) = G_UADDO %0, %1
    %6:_(s64) = G_ANYEXT %4(s8)
    %7:_(s64) = G_ANYEXT %5(s1)
    $r4 = COPY %6(s64)
    $r5 = COPY %7(s64)
    PseudoRET implicit $r4, implicit $r5

...
---
name:            uaddo_i16
body:             |
  bb.1:
    liveins: $r4, $r5

    ; CHECK-LABEL: name: uaddo_i16
    ; CHECK: liveins: $r4, $r5
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $r4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $r5
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:_(s64) = G_ADD [[COPY]], [[COPY1]]
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 65535
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s64) = G_AND [[ADD]], [[C]]
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s64) = G_CONSTANT i64 65535
    ; CHECK-NEXT: [[AND1:%[0-9]+]]:_(s64) = G_AND [[COPY1]], [[C1]]
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:_(s64) = G_ICMP intpred(ult), [[AND]](s64), [[AND1]]
    ; CHECK-NEXT: $r4 = COPY [[ADD]](s64)
    ; CHECK-NEXT: $r5 = COPY [[ICMP]](s64)
    ; CHECK-NEXT: PseudoRET implicit $r4, implicit $r5
    %2:_(s64) = COPY $r4
    %0:_(s16) = G_TRUNC %2(s64)
    %3:_(s64) = COPY $r5
    %1:_(s16) = G_TRUNC %3(s64)
    %4:_(s16), %5:_(s1) = G_UADDO %0, %1
    %6:_(s64) = G_ANYEXT %4(s16)
    %7:_(s64) = G_ANYEXT %5(s1)
    $r4 = COPY %6(s64)
    $r5 = COPY %7(s64)
    PseudoRET implicit $r4, implicit $r5

...
---
name:            uaddo_i32
body:             |
  bb.1:
    liveins: $r4, $r5

    ; CHECK-LABEL: name: uaddo_i32
    ; CHECK: liveins: $r4, $r5
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $r4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $r5
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:_(s64) = G_ADD [[COPY]], [[COPY1]]
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 4294967295
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s64) = G_AND [[ADD]], [[C]]
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s64) = G_CONSTANT i64 4294967295
    ; CHECK-NEXT: [[AND1:%[0-9]+]]:_(s64) = G_AND [[COPY1]], [[C1]]
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:_(s64) = G_ICMP intpred(ult), [[AND]](s64), [[AND1]]
    ; CHECK-NEXT: $r4 = COPY [[ADD]](s64)
    ; CHECK-NEXT: $r5 = COPY [[ICMP]](s64)
    ; CHECK-NEXT: PseudoRET implicit $r4, implicit $r5
    %2:_(s64) = COPY $r4
    %0:_(s32) = G_TRUNC %2(s64)
    %3:_(s64) = COPY $r5
    %1:_(s32) = G_TRUNC %3(s64)
    %4:_(s32), %5:_(s1) = G_UADDO %0, %1
    %6:_(s64) = G_ANYEXT %4(s32)
    %7:_(s64) = G_ANYEXT %5(s1)
    $r4 = COPY %6(s64)
    $r5 = COPY %7(s64)
    PseudoRET implicit $r4, implicit $r5

...
---
name:            uaddo_i64
body:             |
  bb.1:
    liveins: $r4, $r5

    ; CHECK-LABEL: name: uaddo_i64
    ; CHECK: liveins: $r4, $r5
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $r4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $r5
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:_(s64) = G_ADD [[COPY]], [[COPY1]]
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:_(s64) = G_ICMP intpred(ult), [[ADD]](s64), [[COPY1]]
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(s64) = COPY [[ADD]](s64)
    ; CHECK-NEXT: $r4 = COPY [[COPY2]](s64)
    ; CHECK-NEXT: $r5 = COPY [[ICMP]](s64)
    ; CHECK-NEXT: PseudoRET implicit $r4, implicit $r5
    %0:_(s64) = COPY $r4
    %1:_(s64) = COPY $r5
    %2:_(s64), %3:_(s1) = G_UADDO %0, %1
    %4:_(s64) = G_ANYEXT %3(s1)
    $r4 = COPY %2(s64)
    $r5 = COPY %4(s64)
    PseudoRET implicit $r4, implicit $r5

...
---
name:            usubo_i8
body:             |
  bb.1:
    liveins: $r4, $r5

    ; CHECK-LABEL: name: usubo_i8
    ; CHECK: liveins: $r4, $r5
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $r4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $r5
    ; CHECK-NEXT: [[SUB:%[0-9]+]]:_(s64) = G_SUB [[COPY]], [[COPY1]]
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 255
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s64) = G_AND [[COPY]], [[C]]
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s64) = G_CONSTANT i64 255
    ; CHECK-NEXT: [[AND1:%[0-9]+]]:_(s64) = G_AND [[COPY1]], [[C1]]
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:_(s64) = G_ICMP intpred(ult), [[AND]](s64), [[AND1]]
    ; CHECK-NEXT: $r4 = COPY [[SUB]](s64)
    ; CHECK-NEXT: $r5 = COPY [[ICMP]](s64)
    ; CHECK-NEXT: PseudoRET implicit $r4, implicit $r5
    %2:_(s64) = COPY $r4
    %0:_(s8) = G_TRUNC %2(s64)
    %3:_(s64) = COPY $r5
    %1:_(s8) = G_TRUNC %3(s64)
    %4:_(s8), %5:_(s1) = G_USUBO %0, %1
    %6:_(s64) = G_ANYEXT %4(s8)
    %7:_(s64) = G_ANYEXT %5(s1)
    $r4 = COPY %6(s64)
    $r5 = COPY %7(s64)
    PseudoRET implicit $r4, implicit $r5

...
---
name:            usubo_i16
body:             |
  bb.1:
    liveins: $r4, $r5

    ; CHECK-LABEL: name: usubo_i16
    ; CHECK: liveins: $r4, $r5
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $r4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $r5
    ; CHECK-NEXT: [[SUB:%[0-9]+]]:_(s64) = G_SUB [[COPY]], [[COPY1]]
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 65535
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s64) = G_AND [[COPY]], [[C]]
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s64) = G_CONSTANT i64 65535
    ; CHECK-NEXT: [[AND1:%[0-9]+]]:_(s64) = G_AND [[COPY1]], [[C1]]
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:_(s64) = G_ICMP intpred(ult), [[AND]](s64), [[AND1]]
    ; CHECK-NEXT: $r4 = COPY [[SUB]](s64)
    ; CHECK-NEXT: $r5 = COPY [[ICMP]](s64)
    ; CHECK-NEXT: PseudoRET implicit $r4, implicit $r5
    %2:_(s64) = COPY $r4
    %0:_(s16) = G_TRUNC %2(s64)
    %3:_(s64) = COPY $r5
    %1:_(s16) = G_TRUNC %3(s64)
    %4:_(s16), %5:_(s1) = G_USUBO %0, %1
    %6:_(s64) = G_ANYEXT %4(s16)
    %7:_(s64) = G_ANYEXT %5(s1)
    $r4 = COPY %6(s64)
    $r5 = COPY %7(s64)
    PseudoRET implicit $r4, implicit $r5

...
---
name:            usubo_i32
body:             |
  bb.1:
    liveins: $r4, $r5

    ; CHECK-LABEL: name: usubo_i32
    ; CHECK: liveins: $r4, $r5
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $r4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $r5
    ; CHECK-NEXT: [[SUB:%[0-9]+]]:_(s64) = G_SUB [[COPY]], [[COPY1]]
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 4294967295
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s64) = G_AND [[COPY]], [[C]]
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s64) = G_CONSTANT i64 4294967295
    ; CHECK-NEXT: [[AND1:%[0-9]+]]:_(s64) = G_AND [[COPY1]], [[C1]]
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:_(s64) = G_ICMP intpred(ult), [[AND]](s64), [[AND1]]
    ; CHECK-NEXT: $r4 = COPY [[SUB]](s64)
    ; CHECK-NEXT: $r5 = COPY [[ICMP]](s64)
    ; CHECK-NEXT: PseudoRET implicit $r4, implicit $r5
    %2:_(s64) = COPY $r4
    %0:_(s32) = G_TRUNC %2(s64)
    %3:_(s64) = COPY $r5
    %1:_(s32) = G_TRUNC %3(s64)
    %4:_(s32), %5:_(s1) = G_USUBO %0, %1
    %6:_(s64) = G_ANYEXT %4(s32)
    %7:_(s64) = G_ANYEXT %5(s1)
    $r4 = COPY %6(s64)
    $r5 = COPY %7(s64)
    PseudoRET implicit $r4, implicit $r5

...
---
name:            usubo_i64
body:             |
  bb.1:
    liveins: $r4, $r5

    ; CHECK-LABEL: name: usubo_i64
    ; CHECK: liveins: $r4, $r5
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $r4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $r5
    ; CHECK-NEXT: [[SUB:%[0-9]+]]:_(s64) = G_SUB [[COPY]], [[COPY1]]
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:_(s64) = G_ICMP intpred(ult), [[COPY]](s64), [[COPY1]]
    ; CHECK-NEXT: $r4 = COPY [[SUB]](s64)
    ; CHECK-NEXT: $r5 = COPY [[ICMP]](s64)
    ; CHECK-NEXT: PseudoRET implicit $r4, implicit $r5
    %0:_(s64) = COPY $r4
    %1:_(s64) = COPY $r5
    %2:_(s64), %3:_(s1) = G_USUBO %0, %1
    %4:_(s64) = G_ANYEXT %3(s1)
    $r4 = COPY %2(s64)
    $r5 = COPY %4(s64)
    PseudoRET implicit $r4, implicit $r5

...
---
name:            uadde_i8
body:             |
  bb.1:
    liveins: $r4, $r5, $r6

    ; CHECK-LABEL: name: uadde_i8
    ; CHECK: liveins: $r4, $r5, $r6
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $r4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $r5
    ; CHECK-NEXT: %carry_in:_(s64) = COPY $r6
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:_(s64) = G_ADD [[COPY]], [[COPY1]]
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 255
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s64) = G_AND [[ADD]], [[C]]
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s64) = G_CONSTANT i64 255
    ; CHECK-NEXT: [[AND1:%[0-9]+]]:_(s64) = G_AND [[COPY]], [[C1]]
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:_(s64) = G_ICMP intpred(ult), [[AND]](s64), [[AND1]]
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s64) = G_CONSTANT i64 1
    ; CHECK-NEXT: [[AND2:%[0-9]+]]:_(s64) = G_AND %carry_in, [[C2]]
    ; CHECK-NEXT: [[ADD1:%[0-9]+]]:_(s64) = G_ADD [[ADD]], [[AND2]]
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s64) = G_CONSTANT i64 255
    ; CHECK-NEXT: [[AND3:%[0-9]+]]:_(s64) = G_AND [[ADD1]], [[C4]]
    ; CHECK-NEXT: [[ICMP1:%[0-9]+]]:_(s64) = G_ICMP intpred(eq), [[AND3]](s64), [[C3]]
    ; CHECK-NEXT: [[AND4:%[0-9]+]]:_(s64) = G_AND [[ICMP1]], %carry_in
    ; CHECK-NEXT: [[OR:%[0-9]+]]:_(s64) = G_OR [[ICMP]], [[AND4]]
    ; CHECK-NEXT: $r4 = COPY [[ADD1]](s64)
    ; CHECK-NEXT: $r5 = COPY [[OR]](s64)
    ; CHECK-NEXT: PseudoRET implicit $r4, implicit $r5
    %2:_(s64) = COPY $r4
    %0:_(s8) = G_TRUNC %2(s64)
    %3:_(s64) = COPY $r5
    %1:_(s8) = G_TRUNC %3(s64)
    %carry_in:_(s64) = COPY $r6
    %carry_in1:_(s1) = G_TRUNC %carry_in
    %4:_(s8), %5:_(s1) = G_UADDE %0, %1, %carry_in1
    %6:_(s64) = G_ANYEXT %4(s8)
    %7:_(s64) = G_ANYEXT %5(s1)
    $r4 = COPY %6(s64)
    $r5 = COPY %7(s64)
    PseudoRET implicit $r4, implicit $r5

...
---
name:            uadde_i16
body:             |
  bb.1:
    liveins: $r4, $r5, $r6

    ; CHECK-LABEL: name: uadde_i16
    ; CHECK: liveins: $r4, $r5, $r6
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $r4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $r5
    ; CHECK-NEXT: %carry_in:_(s64) = COPY $r6
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:_(s64) = G_ADD [[COPY]], [[COPY1]]
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 65535
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s64) = G_AND [[ADD]], [[C]]
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s64) = G_CONSTANT i64 65535
    ; CHECK-NEXT: [[AND1:%[0-9]+]]:_(s64) = G_AND [[COPY]], [[C1]]
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:_(s64) = G_ICMP intpred(ult), [[AND]](s64), [[AND1]]
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s64) = G_CONSTANT i64 1
    ; CHECK-NEXT: [[AND2:%[0-9]+]]:_(s64) = G_AND %carry_in, [[C2]]
    ; CHECK-NEXT: [[ADD1:%[0-9]+]]:_(s64) = G_ADD [[ADD]], [[AND2]]
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s64) = G_CONSTANT i64 65535
    ; CHECK-NEXT: [[AND3:%[0-9]+]]:_(s64) = G_AND [[ADD1]], [[C4]]
    ; CHECK-NEXT: [[ICMP1:%[0-9]+]]:_(s64) = G_ICMP intpred(eq), [[AND3]](s64), [[C3]]
    ; CHECK-NEXT: [[AND4:%[0-9]+]]:_(s64) = G_AND [[ICMP1]], %carry_in
    ; CHECK-NEXT: [[OR:%[0-9]+]]:_(s64) = G_OR [[ICMP]], [[AND4]]
    ; CHECK-NEXT: $r4 = COPY [[ADD1]](s64)
    ; CHECK-NEXT: $r5 = COPY [[OR]](s64)
    ; CHECK-NEXT: PseudoRET implicit $r4, implicit $r5
    %2:_(s64) = COPY $r4
    %0:_(s16) = G_TRUNC %2(s64)
    %3:_(s64) = COPY $r5
    %1:_(s16) = G_TRUNC %3(s64)
    %carry_in:_(s64) = COPY $r6
    %carry_in1:_(s1) = G_TRUNC %carry_in
    %4:_(s16), %5:_(s1) = G_UADDE %0, %1, %carry_in1
    %6:_(s64) = G_ANYEXT %4(s16)
    %7:_(s64) = G_ANYEXT %5(s1)
    $r4 = COPY %6(s64)
    $r5 = COPY %7(s64)
    PseudoRET implicit $r4, implicit $r5

...
---
name:            uadde_i32
body:             |
  bb.1:
    liveins: $r4, $r5, $r6

    ; CHECK-LABEL: name: uadde_i32
    ; CHECK: liveins: $r4, $r5, $r6
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $r4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $r5
    ; CHECK-NEXT: %carry_in:_(s64) = COPY $r6
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:_(s64) = G_ADD [[COPY]], [[COPY1]]
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 4294967295
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s64) = G_AND [[ADD]], [[C]]
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s64) = G_CONSTANT i64 4294967295
    ; CHECK-NEXT: [[AND1:%[0-9]+]]:_(s64) = G_AND [[COPY]], [[C1]]
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:_(s64) = G_ICMP intpred(ult), [[AND]](s64), [[AND1]]
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s64) = G_CONSTANT i64 1
    ; CHECK-NEXT: [[AND2:%[0-9]+]]:_(s64) = G_AND %carry_in, [[C2]]
    ; CHECK-NEXT: [[ADD1:%[0-9]+]]:_(s64) = G_ADD [[ADD]], [[AND2]]
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s64) = G_CONSTANT i64 4294967295
    ; CHECK-NEXT: [[AND3:%[0-9]+]]:_(s64) = G_AND [[ADD1]], [[C4]]
    ; CHECK-NEXT: [[ICMP1:%[0-9]+]]:_(s64) = G_ICMP intpred(eq), [[AND3]](s64), [[C3]]
    ; CHECK-NEXT: [[AND4:%[0-9]+]]:_(s64) = G_AND [[ICMP1]], %carry_in
    ; CHECK-NEXT: [[OR:%[0-9]+]]:_(s64) = G_OR [[ICMP]], [[AND4]]
    ; CHECK-NEXT: $r4 = COPY [[ADD1]](s64)
    ; CHECK-NEXT: $r5 = COPY [[OR]](s64)
    ; CHECK-NEXT: PseudoRET implicit $r4, implicit $r5
    %2:_(s64) = COPY $r4
    %0:_(s32) = G_TRUNC %2(s64)
    %3:_(s64) = COPY $r5
    %1:_(s32) = G_TRUNC %3(s64)
    %carry_in:_(s64) = COPY $r6
    %carry_in1:_(s1) = G_TRUNC %carry_in
    %4:_(s32), %5:_(s1) = G_UADDE %0, %1, %carry_in1
    %6:_(s64) = G_ANYEXT %4(s32)
    %7:_(s64) = G_ANYEXT %5(s1)
    $r4 = COPY %6(s64)
    $r5 = COPY %7(s64)
    PseudoRET implicit $r4, implicit $r5

...
---
name:            uadde_i64
body:             |
  bb.1:
    liveins: $r4, $r5, $r6

    ; CHECK-LABEL: name: uadde_i64
    ; CHECK: liveins: $r4, $r5, $r6
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $r4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $r5
    ; CHECK-NEXT: %carry_in:_(s64) = COPY $r6
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:_(s64) = G_ADD [[COPY]], [[COPY1]]
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:_(s64) = G_ICMP intpred(ult), [[ADD]](s64), [[COPY]]
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 1
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s64) = G_AND %carry_in, [[C]]
    ; CHECK-NEXT: [[ADD1:%[0-9]+]]:_(s64) = G_ADD [[ADD]], [[AND]]
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
    ; CHECK-NEXT: [[ICMP1:%[0-9]+]]:_(s64) = G_ICMP intpred(eq), [[ADD1]](s64), [[C1]]
    ; CHECK-NEXT: [[AND1:%[0-9]+]]:_(s64) = G_AND [[ICMP1]], %carry_in
    ; CHECK-NEXT: [[OR:%[0-9]+]]:_(s64) = G_OR [[ICMP]], [[AND1]]
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(s64) = COPY [[ADD1]](s64)
    ; CHECK-NEXT: $r4 = COPY [[COPY2]](s64)
    ; CHECK-NEXT: $r5 = COPY [[OR]](s64)
    ; CHECK-NEXT: PseudoRET implicit $r4, implicit $r5
    %0:_(s64) = COPY $r4
    %1:_(s64) = COPY $r5
    %carry_in:_(s64) = COPY $r6
    %carry_in1:_(s1) = G_TRUNC %carry_in
    %2:_(s64), %3:_(s1) = G_UADDE %0, %1, %carry_in1
    %4:_(s64) = G_ANYEXT %3(s1)
    $r4 = COPY %2(s64)
    $r5 = COPY %4(s64)
    PseudoRET implicit $r4, implicit $r5

...
---
name:            usube_i8
body:             |
  bb.1:
    liveins: $r4, $r5, $r6

    ; CHECK-LABEL: name: usube_i8
    ; CHECK: liveins: $r4, $r5, $r6
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $r4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $r5
    ; CHECK-NEXT: %carry_in:_(s64) = COPY $r6
    ; CHECK-NEXT: [[SUB:%[0-9]+]]:_(s64) = G_SUB [[COPY]], [[COPY1]]
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 255
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s64) = G_AND [[SUB]], [[C]]
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s64) = G_CONSTANT i64 255
    ; CHECK-NEXT: [[AND1:%[0-9]+]]:_(s64) = G_AND [[COPY]], [[C1]]
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:_(s64) = G_ICMP intpred(ugt), [[AND]](s64), [[AND1]]
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s64) = G_CONSTANT i64 1
    ; CHECK-NEXT: [[AND2:%[0-9]+]]:_(s64) = G_AND %carry_in, [[C2]]
    ; CHECK-NEXT: [[SUB1:%[0-9]+]]:_(s64) = G_SUB [[SUB]], [[AND2]]
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s64) = G_CONSTANT i64 255
    ; CHECK-NEXT: [[AND3:%[0-9]+]]:_(s64) = G_AND [[SUB]], [[C4]]
    ; CHECK-NEXT: [[ICMP1:%[0-9]+]]:_(s64) = G_ICMP intpred(eq), [[AND3]](s64), [[C3]]
    ; CHECK-NEXT: [[AND4:%[0-9]+]]:_(s64) = G_AND [[ICMP1]], %carry_in
    ; CHECK-NEXT: [[OR:%[0-9]+]]:_(s64) = G_OR [[ICMP]], [[AND4]]
    ; CHECK-NEXT: $r4 = COPY [[SUB1]](s64)
    ; CHECK-NEXT: $r5 = COPY [[OR]](s64)
    ; CHECK-NEXT: PseudoRET implicit $r4, implicit $r5
    %2:_(s64) = COPY $r4
    %0:_(s8) = G_TRUNC %2(s64)
    %3:_(s64) = COPY $r5
    %1:_(s8) = G_TRUNC %3(s64)
    %carry_in:_(s64) = COPY $r6
    %carry_in1:_(s1) = G_TRUNC %carry_in
    %4:_(s8), %5:_(s1) = G_USUBE %0, %1, %carry_in1
    %6:_(s64) = G_ANYEXT %4(s8)
    %7:_(s64) = G_ANYEXT %5(s1)
    $r4 = COPY %6(s64)
    $r5 = COPY %7(s64)
    PseudoRET implicit $r4, implicit $r5

...
---
name:            usube_i16
body:             |
  bb.1:
    liveins: $r4, $r5, $r6

    ; CHECK-LABEL: name: usube_i16
    ; CHECK: liveins: $r4, $r5, $r6
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $r4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $r5
    ; CHECK-NEXT: %carry_in:_(s64) = COPY $r6
    ; CHECK-NEXT: [[SUB:%[0-9]+]]:_(s64) = G_SUB [[COPY]], [[COPY1]]
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 65535
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s64) = G_AND [[SUB]], [[C]]
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s64) = G_CONSTANT i64 65535
    ; CHECK-NEXT: [[AND1:%[0-9]+]]:_(s64) = G_AND [[COPY]], [[C1]]
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:_(s64) = G_ICMP intpred(ugt), [[AND]](s64), [[AND1]]
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s64) = G_CONSTANT i64 1
    ; CHECK-NEXT: [[AND2:%[0-9]+]]:_(s64) = G_AND %carry_in, [[C2]]
    ; CHECK-NEXT: [[SUB1:%[0-9]+]]:_(s64) = G_SUB [[SUB]], [[AND2]]
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s64) = G_CONSTANT i64 65535
    ; CHECK-NEXT: [[AND3:%[0-9]+]]:_(s64) = G_AND [[SUB]], [[C4]]
    ; CHECK-NEXT: [[ICMP1:%[0-9]+]]:_(s64) = G_ICMP intpred(eq), [[AND3]](s64), [[C3]]
    ; CHECK-NEXT: [[AND4:%[0-9]+]]:_(s64) = G_AND [[ICMP1]], %carry_in
    ; CHECK-NEXT: [[OR:%[0-9]+]]:_(s64) = G_OR [[ICMP]], [[AND4]]
    ; CHECK-NEXT: $r4 = COPY [[SUB1]](s64)
    ; CHECK-NEXT: $r5 = COPY [[OR]](s64)
    ; CHECK-NEXT: PseudoRET implicit $r4, implicit $r5
    %2:_(s64) = COPY $r4
    %0:_(s16) = G_TRUNC %2(s64)
    %3:_(s64) = COPY $r5
    %1:_(s16) = G_TRUNC %3(s64)
    %carry_in:_(s64) = COPY $r6
    %carry_in1:_(s1) = G_TRUNC %carry_in
    %4:_(s16), %5:_(s1) = G_USUBE %0, %1, %carry_in1
    %6:_(s64) = G_ANYEXT %4(s16)
    %7:_(s64) = G_ANYEXT %5(s1)
    $r4 = COPY %6(s64)
    $r5 = COPY %7(s64)
    PseudoRET implicit $r4, implicit $r5

...
---
name:            usube_i32
body:             |
  bb.1:
    liveins: $r4, $r5, $r6

    ; CHECK-LABEL: name: usube_i32
    ; CHECK: liveins: $r4, $r5, $r6
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $r4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $r5
    ; CHECK-NEXT: %carry_in:_(s64) = COPY $r6
    ; CHECK-NEXT: [[SUB:%[0-9]+]]:_(s64) = G_SUB [[COPY]], [[COPY1]]
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 4294967295
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s64) = G_AND [[SUB]], [[C]]
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s64) = G_CONSTANT i64 4294967295
    ; CHECK-NEXT: [[AND1:%[0-9]+]]:_(s64) = G_AND [[COPY]], [[C1]]
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:_(s64) = G_ICMP intpred(ugt), [[AND]](s64), [[AND1]]
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s64) = G_CONSTANT i64 1
    ; CHECK-NEXT: [[AND2:%[0-9]+]]:_(s64) = G_AND %carry_in, [[C2]]
    ; CHECK-NEXT: [[SUB1:%[0-9]+]]:_(s64) = G_SUB [[SUB]], [[AND2]]
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s64) = G_CONSTANT i64 4294967295
    ; CHECK-NEXT: [[AND3:%[0-9]+]]:_(s64) = G_AND [[SUB]], [[C4]]
    ; CHECK-NEXT: [[ICMP1:%[0-9]+]]:_(s64) = G_ICMP intpred(eq), [[AND3]](s64), [[C3]]
    ; CHECK-NEXT: [[AND4:%[0-9]+]]:_(s64) = G_AND [[ICMP1]], %carry_in
    ; CHECK-NEXT: [[OR:%[0-9]+]]:_(s64) = G_OR [[ICMP]], [[AND4]]
    ; CHECK-NEXT: $r4 = COPY [[SUB1]](s64)
    ; CHECK-NEXT: $r5 = COPY [[OR]](s64)
    ; CHECK-NEXT: PseudoRET implicit $r4, implicit $r5
    %2:_(s64) = COPY $r4
    %0:_(s32) = G_TRUNC %2(s64)
    %3:_(s64) = COPY $r5
    %1:_(s32) = G_TRUNC %3(s64)
    %carry_in:_(s64) = COPY $r6
    %carry_in1:_(s1) = G_TRUNC %carry_in
    %4:_(s32), %5:_(s1) = G_USUBE %0, %1, %carry_in1
    %6:_(s64) = G_ANYEXT %4(s32)
    %7:_(s64) = G_ANYEXT %5(s1)
    $r4 = COPY %6(s64)
    $r5 = COPY %7(s64)
    PseudoRET implicit $r4, implicit $r5

...
---
name:            usube_i64
body:             |
  bb.1:
    liveins: $r4, $r5, $r6

    ; CHECK-LABEL: name: usube_i64
    ; CHECK: liveins: $r4, $r5, $r6
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $r4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $r5
    ; CHECK-NEXT: %carry_in:_(s64) = COPY $r6
    ; CHECK-NEXT: [[SUB:%[0-9]+]]:_(s64) = G_SUB [[COPY]], [[COPY1]]
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:_(s64) = G_ICMP intpred(ugt), [[SUB]](s64), [[COPY]]
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 1
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s64) = G_AND %carry_in, [[C]]
    ; CHECK-NEXT: [[SUB1:%[0-9]+]]:_(s64) = G_SUB [[SUB]], [[AND]]
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
    ; CHECK-NEXT: [[ICMP1:%[0-9]+]]:_(s64) = G_ICMP intpred(eq), [[SUB]](s64), [[C1]]
    ; CHECK-NEXT: [[AND1:%[0-9]+]]:_(s64) = G_AND [[ICMP1]], %carry_in
    ; CHECK-NEXT: [[OR:%[0-9]+]]:_(s64) = G_OR [[ICMP]], [[AND1]]
    ; CHECK-NEXT: $r4 = COPY [[SUB1]](s64)
    ; CHECK-NEXT: $r5 = COPY [[OR]](s64)
    ; CHECK-NEXT: PseudoRET implicit $r4, implicit $r5
    %0:_(s64) = COPY $r4
    %1:_(s64) = COPY $r5
    %carry_in:_(s64) = COPY $r6
    %carry_in1:_(s1) = G_TRUNC %carry_in
    %2:_(s64), %3:_(s1) = G_USUBE %0, %1, %carry_in1
    %4:_(s64) = G_ANYEXT %3(s1)
    $r4 = COPY %2(s64)
    $r5 = COPY %4(s64)
    PseudoRET implicit $r4, implicit $r5

...
