# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc --mtriple=loongarch32 -run-pass=legalizer %s -o - \
# RUN: | FileCheck %s
---
name:            xor_i7
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: xor_i7
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r5
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:_(s32) = G_XOR [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $r4 = COPY [[XOR]](s32)
    ; CHECK-NEXT: PseudoRET implicit $r4
    %0:_(s32) = COPY $r4
    %1:_(s32) = COPY $r5
    %2:_(s7) = G_TRUNC %0(s32)
    %3:_(s7) = G_TRUNC %1(s32)
    %4:_(s7) = G_XOR %2, %3
    %5:_(s32) = G_ANYEXT %4(s7)
    $r4 = COPY %5(s32)
    PseudoRET implicit $r4

...
---
name:            xor_i8
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: xor_i8
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r5
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:_(s32) = G_XOR [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $r4 = COPY [[XOR]](s32)
    ; CHECK-NEXT: PseudoRET implicit $r4
    %0:_(s32) = COPY $r4
    %1:_(s32) = COPY $r5
    %2:_(s8) = G_TRUNC %0(s32)
    %3:_(s8) = G_TRUNC %1(s32)
    %4:_(s8) = G_XOR %2, %3
    %5:_(s32) = G_ANYEXT %4(s8)
    $r4 = COPY %5(s32)
    PseudoRET implicit $r4

...
---
name:            xor_i16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: xor_i16
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r5
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:_(s32) = G_XOR [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $r4 = COPY [[XOR]](s32)
    ; CHECK-NEXT: PseudoRET implicit $r4
    %0:_(s32) = COPY $r4
    %1:_(s32) = COPY $r5
    %2:_(s16) = G_TRUNC %0(s32)
    %3:_(s16) = G_TRUNC %1(s32)
    %4:_(s16) = G_XOR %2, %3
    %5:_(s32) = G_ANYEXT %4(s16)
    $r4 = COPY %5(s32)
    PseudoRET implicit $r4

...
---
name:            xor_i32
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: xor_i32
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r5
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:_(s32) = G_XOR [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $r4 = COPY [[XOR]](s32)
    ; CHECK-NEXT: PseudoRET implicit $r4
    %0:_(s32) = COPY $r4
    %1:_(s32) = COPY $r5
    %2:_(s32) = G_XOR %0, %1
    $r4 = COPY %2(s32)
    PseudoRET implicit $r4

...
---
name:            xor_i48
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: xor_i48
    ; CHECK: %xlo:_(s32) = COPY $r4
    ; CHECK-NEXT: %xhi:_(s32) = COPY $r5
    ; CHECK-NEXT: %ylo:_(s32) = COPY $r6
    ; CHECK-NEXT: %yhi:_(s32) = COPY $r7
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:_(s32) = G_XOR %xlo, %ylo
    ; CHECK-NEXT: [[XOR1:%[0-9]+]]:_(s32) = G_XOR %xhi, %yhi
    ; CHECK-NEXT: $r4 = COPY [[XOR]](s32)
    ; CHECK-NEXT: $r5 = COPY [[XOR1]](s32)
    ; CHECK-NEXT: PseudoRET implicit $r4, implicit $r5
    %xlo:_(s32) = COPY $r4
    %xhi:_(s32) = COPY $r5
    %ylo:_(s32) = COPY $r6
    %yhi:_(s32) = COPY $r7
    %x0:_(s64) = G_MERGE_VALUES %xlo(s32), %xhi(s32)
    %y0:_(s64) = G_MERGE_VALUES %ylo(s32), %yhi(s32)
    %x:_(s48) = G_TRUNC %x0(s64)
    %y:_(s48) = G_TRUNC %y0(s64)
    %z:_(s48) = G_XOR %x, %y
    %z0:_(s64) = G_ANYEXT %z(s48)
    %zlo:_(s32), %zhi:_(s32) = G_UNMERGE_VALUES %z0(s64)
    $r4 = COPY %zlo(s32)
    $r5 = COPY %zhi(s32)
    PseudoRET implicit $r4, implicit $r5

...
---
name:            xor_i64
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: xor_i64
    ; CHECK: %lo1:_(s32) = COPY $r4
    ; CHECK-NEXT: %hi1:_(s32) = COPY $r5
    ; CHECK-NEXT: %lo2:_(s32) = COPY $r6
    ; CHECK-NEXT: %hi2:_(s32) = COPY $r7
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:_(s32) = G_XOR %lo1, %lo2
    ; CHECK-NEXT: [[XOR1:%[0-9]+]]:_(s32) = G_XOR %hi1, %hi2
    ; CHECK-NEXT: $r4 = COPY [[XOR]](s32)
    ; CHECK-NEXT: $r5 = COPY [[XOR1]](s32)
    ; CHECK-NEXT: PseudoRET implicit $r4, implicit $r5
    %lo1:_(s32) = COPY $r4
    %hi1:_(s32) = COPY $r5
    %lo2:_(s32) = COPY $r6
    %hi2:_(s32) = COPY $r7
    %x1:_(s64) = G_MERGE_VALUES %lo1(s32), %hi1(s32)
    %x2:_(s64) = G_MERGE_VALUES %lo2(s32), %hi2(s32)
    %y:_(s64) = G_XOR %x1, %x2
    %loy:_(s32), %hiy:_(s32) = G_UNMERGE_VALUES %y(s64)
    $r4 = COPY %loy(s32)
    $r5 = COPY %hiy(s32)
    PseudoRET implicit $r4, implicit $r5

...
---
name:            xor_i96
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: xor_i96
    ; CHECK: %lo1:_(s32) = COPY $r4
    ; CHECK-NEXT: %mid1:_(s32) = COPY $r5
    ; CHECK-NEXT: %hi1:_(s32) = COPY $r6
    ; CHECK-NEXT: %lo2:_(s32) = COPY $r7
    ; CHECK-NEXT: %mid2:_(s32) = COPY $r8
    ; CHECK-NEXT: %hi2:_(s32) = COPY $r9
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:_(s32) = G_XOR %lo1, %lo2
    ; CHECK-NEXT: [[XOR1:%[0-9]+]]:_(s32) = G_XOR %mid1, %mid2
    ; CHECK-NEXT: [[XOR2:%[0-9]+]]:_(s32) = G_XOR %hi1, %hi2
    ; CHECK-NEXT: $r4 = COPY [[XOR]](s32)
    ; CHECK-NEXT: $r5 = COPY [[XOR1]](s32)
    ; CHECK-NEXT: $r6 = COPY [[XOR2]](s32)
    ; CHECK-NEXT: PseudoRET implicit $r4, implicit $r5, implicit $r6
    %lo1:_(s32) = COPY $r4
    %mid1:_(s32) = COPY $r5
    %hi1:_(s32) = COPY $r6
    %lo2:_(s32) = COPY $r7
    %mid2:_(s32) = COPY $r8
    %hi2:_(s32) = COPY $r9
    %x1:_(s96) = G_MERGE_VALUES %lo1(s32), %mid1(s32), %hi1(s32)
    %x2:_(s96) = G_MERGE_VALUES %lo2(s32), %mid2(s32), %hi2(s32)
    %y:_(s96) = G_XOR %x1, %x2
    %lo:_(s32), %mid:_(s32), %hi:_(s32) = G_UNMERGE_VALUES %y(s96)
    $r4 = COPY %lo(s32)
    $r5 = COPY %mid(s32)
    $r6 = COPY %hi(s32)
    PseudoRET implicit $r4, implicit $r5, implicit $r6

...
