; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
; RUN: llc --mtriple=loongarch32 -global-isel -stop-after=irtranslator -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=LA32 %s
; RUN: llc --mtriple=loongarch64 -global-isel -stop-after=irtranslator -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=LA64 %s

define void @test_args_i8(i8 %a) {
  ; LA32-LABEL: name: test_args_i8
  ; LA32: bb.1.entry:
  ; LA32-NEXT:   liveins: $r4
  ; LA32-NEXT: {{  $}}
  ; LA32-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r4
  ; LA32-NEXT:   [[TRUNC:%[0-9]+]]:_(s8) = G_TRUNC [[COPY]](s32)
  ; LA32-NEXT:   [[C:%[0-9]+]]:_(s8) = G_CONSTANT i8 1
  ; LA32-NEXT:   [[ADD:%[0-9]+]]:_(s8) = G_ADD [[TRUNC]], [[C]]
  ; LA32-NEXT:   PseudoRET
  ;
  ; LA64-LABEL: name: test_args_i8
  ; LA64: bb.1.entry:
  ; LA64-NEXT:   liveins: $r4
  ; LA64-NEXT: {{  $}}
  ; LA64-NEXT:   [[COPY:%[0-9]+]]:_(s64) = COPY $r4
  ; LA64-NEXT:   [[TRUNC:%[0-9]+]]:_(s8) = G_TRUNC [[COPY]](s64)
  ; LA64-NEXT:   [[C:%[0-9]+]]:_(s8) = G_CONSTANT i8 1
  ; LA64-NEXT:   [[ADD:%[0-9]+]]:_(s8) = G_ADD [[TRUNC]], [[C]]
  ; LA64-NEXT:   PseudoRET
entry:
  %0 = add i8 %a, 1
  ret void
}

define void @test_args_i16(i16 %a) {
  ; LA32-LABEL: name: test_args_i16
  ; LA32: bb.1.entry:
  ; LA32-NEXT:   liveins: $r4
  ; LA32-NEXT: {{  $}}
  ; LA32-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r4
  ; LA32-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[COPY]](s32)
  ; LA32-NEXT:   [[C:%[0-9]+]]:_(s16) = G_CONSTANT i16 1
  ; LA32-NEXT:   [[ADD:%[0-9]+]]:_(s16) = G_ADD [[TRUNC]], [[C]]
  ; LA32-NEXT:   PseudoRET
  ;
  ; LA64-LABEL: name: test_args_i16
  ; LA64: bb.1.entry:
  ; LA64-NEXT:   liveins: $r4
  ; LA64-NEXT: {{  $}}
  ; LA64-NEXT:   [[COPY:%[0-9]+]]:_(s64) = COPY $r4
  ; LA64-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[COPY]](s64)
  ; LA64-NEXT:   [[C:%[0-9]+]]:_(s16) = G_CONSTANT i16 1
  ; LA64-NEXT:   [[ADD:%[0-9]+]]:_(s16) = G_ADD [[TRUNC]], [[C]]
  ; LA64-NEXT:   PseudoRET
entry:
  %0 = add i16 %a, 1
  ret void
}

define void @test_args_i32(i32 %a) {
  ; LA32-LABEL: name: test_args_i32
  ; LA32: bb.1.entry:
  ; LA32-NEXT:   liveins: $r4
  ; LA32-NEXT: {{  $}}
  ; LA32-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r4
  ; LA32-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
  ; LA32-NEXT:   [[ADD:%[0-9]+]]:_(s32) = G_ADD [[COPY]], [[C]]
  ; LA32-NEXT:   PseudoRET
  ;
  ; LA64-LABEL: name: test_args_i32
  ; LA64: bb.1.entry:
  ; LA64-NEXT:   liveins: $r4
  ; LA64-NEXT: {{  $}}
  ; LA64-NEXT:   [[COPY:%[0-9]+]]:_(s64) = COPY $r4
  ; LA64-NEXT:   [[TRUNC:%[0-9]+]]:_(s32) = G_TRUNC [[COPY]](s64)
  ; LA64-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
  ; LA64-NEXT:   [[ADD:%[0-9]+]]:_(s32) = G_ADD [[TRUNC]], [[C]]
  ; LA64-NEXT:   PseudoRET
entry:
  %0 = add i32 %a, 1
  ret void
}

define void @test_args_i64(i64 %a) {
  ; LA32-LABEL: name: test_args_i64
  ; LA32: bb.1.entry:
  ; LA32-NEXT:   liveins: $r4, $r5
  ; LA32-NEXT: {{  $}}
  ; LA32-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r4
  ; LA32-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $r5
  ; LA32-NEXT:   [[MV:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[COPY]](s32), [[COPY1]](s32)
  ; LA32-NEXT:   [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 1
  ; LA32-NEXT:   [[ADD:%[0-9]+]]:_(s64) = G_ADD [[MV]], [[C]]
  ; LA32-NEXT:   PseudoRET
  ;
  ; LA64-LABEL: name: test_args_i64
  ; LA64: bb.1.entry:
  ; LA64-NEXT:   liveins: $r4
  ; LA64-NEXT: {{  $}}
  ; LA64-NEXT:   [[COPY:%[0-9]+]]:_(s64) = COPY $r4
  ; LA64-NEXT:   [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 1
  ; LA64-NEXT:   [[ADD:%[0-9]+]]:_(s64) = G_ADD [[COPY]], [[C]]
  ; LA64-NEXT:   PseudoRET
entry:
  %0 = add i64 %a, 1
  ret void
}

define void @test_args_i8_ptr(ptr %a) {
  ; LA32-LABEL: name: test_args_i8_ptr
  ; LA32: bb.1.entry:
  ; LA32-NEXT:   liveins: $r4
  ; LA32-NEXT: {{  $}}
  ; LA32-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $r4
  ; LA32-NEXT:   [[LOAD:%[0-9]+]]:_(s8) = G_LOAD [[COPY]](p0) :: (load (s8) from %ir.a)
  ; LA32-NEXT:   PseudoRET
  ;
  ; LA64-LABEL: name: test_args_i8_ptr
  ; LA64: bb.1.entry:
  ; LA64-NEXT:   liveins: $r4
  ; LA64-NEXT: {{  $}}
  ; LA64-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $r4
  ; LA64-NEXT:   [[LOAD:%[0-9]+]]:_(s8) = G_LOAD [[COPY]](p0) :: (load (s8) from %ir.a)
  ; LA64-NEXT:   PseudoRET
entry:
  %0 = load i8, ptr %a
  ret void
}

define void @test_args_2xi8(i8 %a, i8 %b) {
  ; LA32-LABEL: name: test_args_2xi8
  ; LA32: bb.1.entry:
  ; LA32-NEXT:   liveins: $r4, $r5
  ; LA32-NEXT: {{  $}}
  ; LA32-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r4
  ; LA32-NEXT:   [[TRUNC:%[0-9]+]]:_(s8) = G_TRUNC [[COPY]](s32)
  ; LA32-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $r5
  ; LA32-NEXT:   [[TRUNC1:%[0-9]+]]:_(s8) = G_TRUNC [[COPY1]](s32)
  ; LA32-NEXT:   [[ADD:%[0-9]+]]:_(s8) = G_ADD [[TRUNC]], [[TRUNC1]]
  ; LA32-NEXT:   PseudoRET
  ;
  ; LA64-LABEL: name: test_args_2xi8
  ; LA64: bb.1.entry:
  ; LA64-NEXT:   liveins: $r4, $r5
  ; LA64-NEXT: {{  $}}
  ; LA64-NEXT:   [[COPY:%[0-9]+]]:_(s64) = COPY $r4
  ; LA64-NEXT:   [[TRUNC:%[0-9]+]]:_(s8) = G_TRUNC [[COPY]](s64)
  ; LA64-NEXT:   [[COPY1:%[0-9]+]]:_(s64) = COPY $r5
  ; LA64-NEXT:   [[TRUNC1:%[0-9]+]]:_(s8) = G_TRUNC [[COPY1]](s64)
  ; LA64-NEXT:   [[ADD:%[0-9]+]]:_(s8) = G_ADD [[TRUNC]], [[TRUNC1]]
  ; LA64-NEXT:   PseudoRET
entry:
  %0 = add i8 %a, %b
  ret void
}

define void @test_args_2xi16(i16 %a, i16 %b) {
  ; LA32-LABEL: name: test_args_2xi16
  ; LA32: bb.1.entry:
  ; LA32-NEXT:   liveins: $r4, $r5
  ; LA32-NEXT: {{  $}}
  ; LA32-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r4
  ; LA32-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[COPY]](s32)
  ; LA32-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $r5
  ; LA32-NEXT:   [[TRUNC1:%[0-9]+]]:_(s16) = G_TRUNC [[COPY1]](s32)
  ; LA32-NEXT:   [[ADD:%[0-9]+]]:_(s16) = G_ADD [[TRUNC]], [[TRUNC1]]
  ; LA32-NEXT:   PseudoRET
  ;
  ; LA64-LABEL: name: test_args_2xi16
  ; LA64: bb.1.entry:
  ; LA64-NEXT:   liveins: $r4, $r5
  ; LA64-NEXT: {{  $}}
  ; LA64-NEXT:   [[COPY:%[0-9]+]]:_(s64) = COPY $r4
  ; LA64-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[COPY]](s64)
  ; LA64-NEXT:   [[COPY1:%[0-9]+]]:_(s64) = COPY $r5
  ; LA64-NEXT:   [[TRUNC1:%[0-9]+]]:_(s16) = G_TRUNC [[COPY1]](s64)
  ; LA64-NEXT:   [[ADD:%[0-9]+]]:_(s16) = G_ADD [[TRUNC]], [[TRUNC1]]
  ; LA64-NEXT:   PseudoRET
entry:
  %0 = add i16 %a, %b
  ret void
}

define void @test_args_2xi32(i32 %a, i32 %b) {
  ; LA32-LABEL: name: test_args_2xi32
  ; LA32: bb.1.entry:
  ; LA32-NEXT:   liveins: $r4, $r5
  ; LA32-NEXT: {{  $}}
  ; LA32-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r4
  ; LA32-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $r5
  ; LA32-NEXT:   [[ADD:%[0-9]+]]:_(s32) = G_ADD [[COPY]], [[COPY1]]
  ; LA32-NEXT:   PseudoRET
  ;
  ; LA64-LABEL: name: test_args_2xi32
  ; LA64: bb.1.entry:
  ; LA64-NEXT:   liveins: $r4, $r5
  ; LA64-NEXT: {{  $}}
  ; LA64-NEXT:   [[COPY:%[0-9]+]]:_(s64) = COPY $r4
  ; LA64-NEXT:   [[TRUNC:%[0-9]+]]:_(s32) = G_TRUNC [[COPY]](s64)
  ; LA64-NEXT:   [[COPY1:%[0-9]+]]:_(s64) = COPY $r5
  ; LA64-NEXT:   [[TRUNC1:%[0-9]+]]:_(s32) = G_TRUNC [[COPY1]](s64)
  ; LA64-NEXT:   [[ADD:%[0-9]+]]:_(s32) = G_ADD [[TRUNC]], [[TRUNC1]]
  ; LA64-NEXT:   PseudoRET
entry:
  %0 = add i32 %a, %b
  ret void
}

define void @test_args_2xi64(i64 %a, i64 %b) {
  ; LA32-LABEL: name: test_args_2xi64
  ; LA32: bb.1.entry:
  ; LA32-NEXT:   liveins: $r4, $r5, $r6, $r7
  ; LA32-NEXT: {{  $}}
  ; LA32-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r4
  ; LA32-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $r5
  ; LA32-NEXT:   [[MV:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[COPY]](s32), [[COPY1]](s32)
  ; LA32-NEXT:   [[COPY2:%[0-9]+]]:_(s32) = COPY $r6
  ; LA32-NEXT:   [[COPY3:%[0-9]+]]:_(s32) = COPY $r7
  ; LA32-NEXT:   [[MV1:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[COPY2]](s32), [[COPY3]](s32)
  ; LA32-NEXT:   [[ADD:%[0-9]+]]:_(s64) = G_ADD [[MV]], [[MV1]]
  ; LA32-NEXT:   PseudoRET
  ;
  ; LA64-LABEL: name: test_args_2xi64
  ; LA64: bb.1.entry:
  ; LA64-NEXT:   liveins: $r4, $r5
  ; LA64-NEXT: {{  $}}
  ; LA64-NEXT:   [[COPY:%[0-9]+]]:_(s64) = COPY $r4
  ; LA64-NEXT:   [[COPY1:%[0-9]+]]:_(s64) = COPY $r5
  ; LA64-NEXT:   [[ADD:%[0-9]+]]:_(s64) = G_ADD [[COPY]], [[COPY1]]
  ; LA64-NEXT:   PseudoRET
entry:
  %0 = add i64 %a, %b
  ret void
}

define void @test_args_2xi8_ptr(ptr %a, ptr %b) {
  ; LA32-LABEL: name: test_args_2xi8_ptr
  ; LA32: bb.1.entry:
  ; LA32-NEXT:   liveins: $r4, $r5
  ; LA32-NEXT: {{  $}}
  ; LA32-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $r4
  ; LA32-NEXT:   [[COPY1:%[0-9]+]]:_(p0) = COPY $r5
  ; LA32-NEXT:   [[LOAD:%[0-9]+]]:_(s8) = G_LOAD [[COPY]](p0) :: (load (s8) from %ir.a)
  ; LA32-NEXT:   [[LOAD1:%[0-9]+]]:_(s8) = G_LOAD [[COPY1]](p0) :: (load (s8) from %ir.b)
  ; LA32-NEXT:   PseudoRET
  ;
  ; LA64-LABEL: name: test_args_2xi8_ptr
  ; LA64: bb.1.entry:
  ; LA64-NEXT:   liveins: $r4, $r5
  ; LA64-NEXT: {{  $}}
  ; LA64-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $r4
  ; LA64-NEXT:   [[COPY1:%[0-9]+]]:_(p0) = COPY $r5
  ; LA64-NEXT:   [[LOAD:%[0-9]+]]:_(s8) = G_LOAD [[COPY]](p0) :: (load (s8) from %ir.a)
  ; LA64-NEXT:   [[LOAD1:%[0-9]+]]:_(s8) = G_LOAD [[COPY1]](p0) :: (load (s8) from %ir.b)
  ; LA64-NEXT:   PseudoRET
entry:
  %0 = load i8, ptr %a
  %1 = load i8, ptr %b
  ret void
}

define void @test_args_ptr_byval(ptr byval(i8) %a) {
  ; LA32-LABEL: name: test_args_ptr_byval
  ; LA32: bb.1.entry:
  ; LA32-NEXT:   liveins: $r4
  ; LA32-NEXT: {{  $}}
  ; LA32-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $r4
  ; LA32-NEXT:   [[LOAD:%[0-9]+]]:_(s8) = G_LOAD [[COPY]](p0) :: (dereferenceable load (s8) from %ir.a)
  ; LA32-NEXT:   PseudoRET
  ;
  ; LA64-LABEL: name: test_args_ptr_byval
  ; LA64: bb.1.entry:
  ; LA64-NEXT:   liveins: $r4
  ; LA64-NEXT: {{  $}}
  ; LA64-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $r4
  ; LA64-NEXT:   [[LOAD:%[0-9]+]]:_(s8) = G_LOAD [[COPY]](p0) :: (dereferenceable load (s8) from %ir.a)
  ; LA64-NEXT:   PseudoRET
entry:
  %0 = load i8, ptr %a
  ret void
}

define void @test_args_ptr_sret(ptr sret(i8) %a) {
  ; LA32-LABEL: name: test_args_ptr_sret
  ; LA32: bb.1.entry:
  ; LA32-NEXT:   liveins: $r4
  ; LA32-NEXT: {{  $}}
  ; LA32-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $r4
  ; LA32-NEXT:   [[LOAD:%[0-9]+]]:_(s8) = G_LOAD [[COPY]](p0) :: (dereferenceable load (s8) from %ir.a)
  ; LA32-NEXT:   PseudoRET
  ;
  ; LA64-LABEL: name: test_args_ptr_sret
  ; LA64: bb.1.entry:
  ; LA64-NEXT:   liveins: $r4
  ; LA64-NEXT: {{  $}}
  ; LA64-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $r4
  ; LA64-NEXT:   [[LOAD:%[0-9]+]]:_(s8) = G_LOAD [[COPY]](p0) :: (dereferenceable load (s8) from %ir.a)
  ; LA64-NEXT:   PseudoRET
entry:
  %0 = load i8, ptr %a
  ret void
}
