# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc --mtriple=loongarch32 -run-pass=regbankselect \
# RUN:   -simplify-mir -verify-machineinstrs %s \
# RUN:   -o - | FileCheck -check-prefix=LA32 %s

---
name:            add_i32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r4, $r5

    ; LA32-LABEL: name: add_i32
    ; LA32: liveins: $r4, $r5
    ; LA32-NEXT: {{  $}}
    ; LA32-NEXT: [[COPY:%[0-9]+]]:gprb(s32) = COPY $r4
    ; LA32-NEXT: [[COPY1:%[0-9]+]]:gprb(s32) = COPY $r5
    ; LA32-NEXT: [[ADD:%[0-9]+]]:gprb(s32) = G_ADD [[COPY]], [[COPY1]]
    ; LA32-NEXT: $r4 = COPY [[ADD]](s32)
    ; LA32-NEXT: PseudoRET implicit $r4
    %0:_(s32) = COPY $r4
    %1:_(s32) = COPY $r5
    %2:_(s32) = G_ADD %0, %1
    $r4 = COPY %2(s32)
    PseudoRET implicit $r4

...
---
name:            sub_i32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r4, $r5

    ; LA32-LABEL: name: sub_i32
    ; LA32: liveins: $r4, $r5
    ; LA32-NEXT: {{  $}}
    ; LA32-NEXT: [[COPY:%[0-9]+]]:gprb(s32) = COPY $r4
    ; LA32-NEXT: [[COPY1:%[0-9]+]]:gprb(s32) = COPY $r5
    ; LA32-NEXT: [[SUB:%[0-9]+]]:gprb(s32) = G_SUB [[COPY]], [[COPY1]]
    ; LA32-NEXT: $r4 = COPY [[SUB]](s32)
    ; LA32-NEXT: PseudoRET implicit $r4
    %0:_(s32) = COPY $r4
    %1:_(s32) = COPY $r5
    %2:_(s32) = G_SUB %0, %1
    $r4 = COPY %2(s32)
    PseudoRET implicit $r4

...
---
name:            shl_i32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r4, $r5

    ; LA32-LABEL: name: shl_i32
    ; LA32: liveins: $r4, $r5
    ; LA32-NEXT: {{  $}}
    ; LA32-NEXT: [[COPY:%[0-9]+]]:gprb(s32) = COPY $r4
    ; LA32-NEXT: [[COPY1:%[0-9]+]]:gprb(s32) = COPY $r5
    ; LA32-NEXT: [[SHL:%[0-9]+]]:gprb(s32) = G_SHL [[COPY]], [[COPY1]](s32)
    ; LA32-NEXT: $r4 = COPY [[SHL]](s32)
    ; LA32-NEXT: PseudoRET implicit $r4
    %0:_(s32) = COPY $r4
    %1:_(s32) = COPY $r5
    %2:_(s32) = G_SHL %0, %1
    $r4 = COPY %2(s32)
    PseudoRET implicit $r4

...
---
name:            ashr_i32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r4, $r5

    ; LA32-LABEL: name: ashr_i32
    ; LA32: liveins: $r4, $r5
    ; LA32-NEXT: {{  $}}
    ; LA32-NEXT: [[COPY:%[0-9]+]]:gprb(s32) = COPY $r4
    ; LA32-NEXT: [[COPY1:%[0-9]+]]:gprb(s32) = COPY $r5
    ; LA32-NEXT: [[ASHR:%[0-9]+]]:gprb(s32) = G_ASHR [[COPY]], [[COPY1]](s32)
    ; LA32-NEXT: $r4 = COPY [[ASHR]](s32)
    ; LA32-NEXT: PseudoRET implicit $r4
    %0:_(s32) = COPY $r4
    %1:_(s32) = COPY $r5
    %2:_(s32) = G_ASHR %0, %1
    $r4 = COPY %2(s32)
    PseudoRET implicit $r4

...
---
name:            lshr_i32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r4, $r5

    ; LA32-LABEL: name: lshr_i32
    ; LA32: liveins: $r4, $r5
    ; LA32-NEXT: {{  $}}
    ; LA32-NEXT: [[COPY:%[0-9]+]]:gprb(s32) = COPY $r4
    ; LA32-NEXT: [[COPY1:%[0-9]+]]:gprb(s32) = COPY $r5
    ; LA32-NEXT: [[LSHR:%[0-9]+]]:gprb(s32) = G_LSHR [[COPY]], [[COPY1]](s32)
    ; LA32-NEXT: $r4 = COPY [[LSHR]](s32)
    ; LA32-NEXT: PseudoRET implicit $r4
    %0:_(s32) = COPY $r4
    %1:_(s32) = COPY $r5
    %2:_(s32) = G_LSHR %0, %1
    $r4 = COPY %2(s32)
    PseudoRET implicit $r4

...
---
name:            and_i32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r4, $r5

    ; LA32-LABEL: name: and_i32
    ; LA32: liveins: $r4, $r5
    ; LA32-NEXT: {{  $}}
    ; LA32-NEXT: [[COPY:%[0-9]+]]:gprb(s32) = COPY $r4
    ; LA32-NEXT: [[COPY1:%[0-9]+]]:gprb(s32) = COPY $r5
    ; LA32-NEXT: [[AND:%[0-9]+]]:gprb(s32) = G_AND [[COPY]], [[COPY1]]
    ; LA32-NEXT: $r4 = COPY [[AND]](s32)
    ; LA32-NEXT: PseudoRET implicit $r4
    %0:_(s32) = COPY $r4
    %1:_(s32) = COPY $r5
    %2:_(s32) = G_AND %0, %1
    $r4 = COPY %2(s32)
    PseudoRET implicit $r4

...
---
name:            or_i32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r4, $r5

    ; LA32-LABEL: name: or_i32
    ; LA32: liveins: $r4, $r5
    ; LA32-NEXT: {{  $}}
    ; LA32-NEXT: [[COPY:%[0-9]+]]:gprb(s32) = COPY $r4
    ; LA32-NEXT: [[COPY1:%[0-9]+]]:gprb(s32) = COPY $r5
    ; LA32-NEXT: [[OR:%[0-9]+]]:gprb(s32) = G_OR [[COPY]], [[COPY1]]
    ; LA32-NEXT: $r4 = COPY [[OR]](s32)
    ; LA32-NEXT: PseudoRET implicit $r4
    %0:_(s32) = COPY $r4
    %1:_(s32) = COPY $r5
    %2:_(s32) = G_OR %0, %1
    $r4 = COPY %2(s32)
    PseudoRET implicit $r4

...
---
name:            xor_i32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r4, $r5

    ; LA32-LABEL: name: xor_i32
    ; LA32: liveins: $r4, $r5
    ; LA32-NEXT: {{  $}}
    ; LA32-NEXT: [[COPY:%[0-9]+]]:gprb(s32) = COPY $r4
    ; LA32-NEXT: [[COPY1:%[0-9]+]]:gprb(s32) = COPY $r5
    ; LA32-NEXT: [[XOR:%[0-9]+]]:gprb(s32) = G_XOR [[COPY]], [[COPY1]]
    ; LA32-NEXT: $r4 = COPY [[XOR]](s32)
    ; LA32-NEXT: PseudoRET implicit $r4
    %0:_(s32) = COPY $r4
    %1:_(s32) = COPY $r5
    %2:_(s32) = G_XOR %0, %1
    $r4 = COPY %2(s32)
    PseudoRET implicit $r4

...
---
name:            icmp_i32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r4, $r5

    ; LA32-LABEL: name: icmp_i32
    ; LA32: liveins: $r4, $r5
    ; LA32-NEXT: {{  $}}
    ; LA32-NEXT: [[COPY:%[0-9]+]]:gprb(s32) = COPY $r4
    ; LA32-NEXT: [[COPY1:%[0-9]+]]:gprb(s32) = COPY $r5
    ; LA32-NEXT: [[ICMP:%[0-9]+]]:gprb(s32) = G_ICMP intpred(eq), [[COPY]](s32), [[COPY1]]
    ; LA32-NEXT: $r4 = COPY [[ICMP]](s32)
    ; LA32-NEXT: PseudoRET implicit $r4
    %0:_(s32) = COPY $r4
    %1:_(s32) = COPY $r5
    %2:_(s32) = G_ICMP intpred(eq), %0(s32), %1
    $r4 = COPY %2(s32)
    PseudoRET implicit $r4

...
---
name:            icmp_ptr
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r4, $r5

    ; LA32-LABEL: name: icmp_ptr
    ; LA32: liveins: $r4, $r5
    ; LA32-NEXT: {{  $}}
    ; LA32-NEXT: [[COPY:%[0-9]+]]:gprb(p0) = COPY $r4
    ; LA32-NEXT: [[COPY1:%[0-9]+]]:gprb(p0) = COPY $r5
    ; LA32-NEXT: [[ICMP:%[0-9]+]]:gprb(s32) = G_ICMP intpred(eq), [[COPY]](p0), [[COPY1]]
    ; LA32-NEXT: $r4 = COPY [[ICMP]](s32)
    ; LA32-NEXT: PseudoRET implicit $r4
    %0:_(p0) = COPY $r4
    %1:_(p0) = COPY $r5
    %2:_(s32) = G_ICMP intpred(eq), %0(p0), %1
    $r4 = COPY %2(s32)
    PseudoRET implicit $r4

...
---
name:            sext_inreg_i32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r4

    ; LA32-LABEL: name: sext_inreg_i32
    ; LA32: liveins: $r4
    ; LA32-NEXT: {{  $}}
    ; LA32-NEXT: [[COPY:%[0-9]+]]:gprb(s32) = COPY $r4
    ; LA32-NEXT: [[SEXT_INREG:%[0-9]+]]:gprb(s32) = G_SEXT_INREG [[COPY]], 16
    ; LA32-NEXT: $r4 = COPY [[SEXT_INREG]](s32)
    ; LA32-NEXT: PseudoRET implicit $r4
    %0:_(s32) = COPY $r4
    %1:_(s32) = G_SEXT_INREG %0, 16
    $r4 = COPY %1(s32)
    PseudoRET implicit $r4

...
