# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc --mtriple=loongarch64 -run-pass=regbankselect \
# RUN:   -simplify-mir -verify-machineinstrs %s \
# RUN:   -o - | FileCheck -check-prefix=LA64 %s

---
name:            add_i64
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r4, $r5

    ; LA64-LABEL: name: add_i64
    ; LA64: liveins: $r4, $r5
    ; LA64-NEXT: {{  $}}
    ; LA64-NEXT: [[COPY:%[0-9]+]]:gprb(s64) = COPY $r4
    ; LA64-NEXT: [[COPY1:%[0-9]+]]:gprb(s64) = COPY $r5
    ; LA64-NEXT: [[ADD:%[0-9]+]]:gprb(s64) = G_ADD [[COPY]], [[COPY1]]
    ; LA64-NEXT: $r4 = COPY [[ADD]](s64)
    ; LA64-NEXT: PseudoRET implicit $r4
    %0:_(s64) = COPY $r4
    %1:_(s64) = COPY $r5
    %2:_(s64) = G_ADD %0, %1
    $r4 = COPY %2(s64)
    PseudoRET implicit $r4

...
---
name:            sub_i64
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r4, $r5

    ; LA64-LABEL: name: sub_i64
    ; LA64: liveins: $r4, $r5
    ; LA64-NEXT: {{  $}}
    ; LA64-NEXT: [[COPY:%[0-9]+]]:gprb(s64) = COPY $r4
    ; LA64-NEXT: [[COPY1:%[0-9]+]]:gprb(s64) = COPY $r5
    ; LA64-NEXT: [[SUB:%[0-9]+]]:gprb(s64) = G_SUB [[COPY]], [[COPY1]]
    ; LA64-NEXT: $r4 = COPY [[SUB]](s64)
    ; LA64-NEXT: PseudoRET implicit $r4
    %0:_(s64) = COPY $r4
    %1:_(s64) = COPY $r5
    %2:_(s64) = G_SUB %0, %1
    $r4 = COPY %2(s64)
    PseudoRET implicit $r4

...
---
name:            shl_i64
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r4, $r5

    ; LA64-LABEL: name: shl_i64
    ; LA64: liveins: $r4, $r5
    ; LA64-NEXT: {{  $}}
    ; LA64-NEXT: [[COPY:%[0-9]+]]:gprb(s64) = COPY $r4
    ; LA64-NEXT: [[COPY1:%[0-9]+]]:gprb(s64) = COPY $r5
    ; LA64-NEXT: [[SHL:%[0-9]+]]:gprb(s64) = G_SHL [[COPY]], [[COPY1]](s64)
    ; LA64-NEXT: $r4 = COPY [[SHL]](s64)
    ; LA64-NEXT: PseudoRET implicit $r4
    %0:_(s64) = COPY $r4
    %1:_(s64) = COPY $r5
    %2:_(s64) = G_SHL %0, %1
    $r4 = COPY %2(s64)
    PseudoRET implicit $r4

...
---
name:            ashr_i64
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r4, $r5

    ; LA64-LABEL: name: ashr_i64
    ; LA64: liveins: $r4, $r5
    ; LA64-NEXT: {{  $}}
    ; LA64-NEXT: [[COPY:%[0-9]+]]:gprb(s64) = COPY $r4
    ; LA64-NEXT: [[COPY1:%[0-9]+]]:gprb(s64) = COPY $r5
    ; LA64-NEXT: [[ASHR:%[0-9]+]]:gprb(s64) = G_ASHR [[COPY]], [[COPY1]](s64)
    ; LA64-NEXT: $r4 = COPY [[ASHR]](s64)
    ; LA64-NEXT: PseudoRET implicit $r4
    %0:_(s64) = COPY $r4
    %1:_(s64) = COPY $r5
    %2:_(s64) = G_ASHR %0, %1
    $r4 = COPY %2(s64)
    PseudoRET implicit $r4

...
---
name:            lshr_i64
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r4, $r5

    ; LA64-LABEL: name: lshr_i64
    ; LA64: liveins: $r4, $r5
    ; LA64-NEXT: {{  $}}
    ; LA64-NEXT: [[COPY:%[0-9]+]]:gprb(s64) = COPY $r4
    ; LA64-NEXT: [[COPY1:%[0-9]+]]:gprb(s64) = COPY $r5
    ; LA64-NEXT: [[LSHR:%[0-9]+]]:gprb(s64) = G_LSHR [[COPY]], [[COPY1]](s64)
    ; LA64-NEXT: $r4 = COPY [[LSHR]](s64)
    ; LA64-NEXT: PseudoRET implicit $r4
    %0:_(s64) = COPY $r4
    %1:_(s64) = COPY $r5
    %2:_(s64) = G_LSHR %0, %1
    $r4 = COPY %2(s64)
    PseudoRET implicit $r4

...
---
name:            and_i64
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r4, $r5

    ; LA64-LABEL: name: and_i64
    ; LA64: liveins: $r4, $r5
    ; LA64-NEXT: {{  $}}
    ; LA64-NEXT: [[COPY:%[0-9]+]]:gprb(s64) = COPY $r4
    ; LA64-NEXT: [[COPY1:%[0-9]+]]:gprb(s64) = COPY $r5
    ; LA64-NEXT: [[AND:%[0-9]+]]:gprb(s64) = G_AND [[COPY]], [[COPY1]]
    ; LA64-NEXT: $r4 = COPY [[AND]](s64)
    ; LA64-NEXT: PseudoRET implicit $r4
    %0:_(s64) = COPY $r4
    %1:_(s64) = COPY $r5
    %2:_(s64) = G_AND %0, %1
    $r4 = COPY %2(s64)
    PseudoRET implicit $r4

...
---
name:            or_i64
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r4, $r5

    ; LA64-LABEL: name: or_i64
    ; LA64: liveins: $r4, $r5
    ; LA64-NEXT: {{  $}}
    ; LA64-NEXT: [[COPY:%[0-9]+]]:gprb(s64) = COPY $r4
    ; LA64-NEXT: [[COPY1:%[0-9]+]]:gprb(s64) = COPY $r5
    ; LA64-NEXT: [[OR:%[0-9]+]]:gprb(s64) = G_OR [[COPY]], [[COPY1]]
    ; LA64-NEXT: $r4 = COPY [[OR]](s64)
    ; LA64-NEXT: PseudoRET implicit $r4
    %0:_(s64) = COPY $r4
    %1:_(s64) = COPY $r5
    %2:_(s64) = G_OR %0, %1
    $r4 = COPY %2(s64)
    PseudoRET implicit $r4

...
---
name:            xor_i64
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r4, $r5

    ; LA64-LABEL: name: xor_i64
    ; LA64: liveins: $r4, $r5
    ; LA64-NEXT: {{  $}}
    ; LA64-NEXT: [[COPY:%[0-9]+]]:gprb(s64) = COPY $r4
    ; LA64-NEXT: [[COPY1:%[0-9]+]]:gprb(s64) = COPY $r5
    ; LA64-NEXT: [[XOR:%[0-9]+]]:gprb(s64) = G_XOR [[COPY]], [[COPY1]]
    ; LA64-NEXT: $r4 = COPY [[XOR]](s64)
    ; LA64-NEXT: PseudoRET implicit $r4
    %0:_(s64) = COPY $r4
    %1:_(s64) = COPY $r5
    %2:_(s64) = G_XOR %0, %1
    $r4 = COPY %2(s64)
    PseudoRET implicit $r4

...
---
name:            icmp_i64
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r4, $r5

    ; LA64-LABEL: name: icmp_i64
    ; LA64: liveins: $r4, $r5
    ; LA64-NEXT: {{  $}}
    ; LA64-NEXT: [[COPY:%[0-9]+]]:gprb(s64) = COPY $r4
    ; LA64-NEXT: [[COPY1:%[0-9]+]]:gprb(s64) = COPY $r5
    ; LA64-NEXT: [[ICMP:%[0-9]+]]:gprb(s64) = G_ICMP intpred(eq), [[COPY]](s64), [[COPY1]]
    ; LA64-NEXT: $r4 = COPY [[ICMP]](s64)
    ; LA64-NEXT: PseudoRET implicit $r4
    %0:_(s64) = COPY $r4
    %1:_(s64) = COPY $r5
    %2:_(s64) = G_ICMP intpred(eq), %0(s64), %1
    $r4 = COPY %2(s64)
    PseudoRET implicit $r4

...
---
name:            icmp_ptr
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r4, $r5

    ; LA64-LABEL: name: icmp_ptr
    ; LA64: liveins: $r4, $r5
    ; LA64-NEXT: {{  $}}
    ; LA64-NEXT: [[COPY:%[0-9]+]]:gprb(p0) = COPY $r4
    ; LA64-NEXT: [[COPY1:%[0-9]+]]:gprb(p0) = COPY $r5
    ; LA64-NEXT: [[ICMP:%[0-9]+]]:gprb(s64) = G_ICMP intpred(eq), [[COPY]](p0), [[COPY1]]
    ; LA64-NEXT: $r4 = COPY [[ICMP]](s64)
    ; LA64-NEXT: PseudoRET implicit $r4
    %0:_(p0) = COPY $r4
    %1:_(p0) = COPY $r5
    %2:_(s64) = G_ICMP intpred(eq), %0(p0), %1
    $r4 = COPY %2(s64)
    PseudoRET implicit $r4

...
---
name:            sext_inreg_i64
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r4

    ; LA64-LABEL: name: sext_inreg_i64
    ; LA64: liveins: $r4
    ; LA64-NEXT: {{  $}}
    ; LA64-NEXT: [[COPY:%[0-9]+]]:gprb(s64) = COPY $r4
    ; LA64-NEXT: [[SEXT_INREG:%[0-9]+]]:gprb(s64) = G_SEXT_INREG [[COPY]], 32
    ; LA64-NEXT: $r4 = COPY [[SEXT_INREG]](s64)
    ; LA64-NEXT: PseudoRET implicit $r4
    %0:_(s64) = COPY $r4
    %1:_(s64) = G_SEXT_INREG %0, 32
    $r4 = COPY %1(s64)
    PseudoRET implicit $r4

...
