# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc --mtriple=loongarch32 -run-pass=regbankselect \
# RUN:   -simplify-mir -verify-machineinstrs %s \
# RUN:   -o - | FileCheck -check-prefix=LA32 %s

---
name:            virt_to_phys
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:

    ; LA32-LABEL: name: virt_to_phys
    ; LA32: [[C:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 1
    ; LA32-NEXT: $r4 = COPY [[C]](s32)
    ; LA32-NEXT: PseudoRET implicit $r4
    %0:_(s32) = G_CONSTANT i32 1
    $r4 = COPY %0(s32)
    PseudoRET implicit $r4

...
---
name:            phys_to_phys
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r4, $r5

    ; LA32-LABEL: name: phys_to_phys
    ; LA32: liveins: $r4, $r5
    ; LA32-NEXT: {{  $}}
    ; LA32-NEXT: $r4 = COPY $r5
    ; LA32-NEXT: PseudoRET implicit $r4
    $r4 = COPY $r5
    PseudoRET implicit $r4

...
---
name:            virt_to_virt
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:

    ; LA32-LABEL: name: virt_to_virt
    ; LA32: [[C:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 1
    ; LA32-NEXT: [[COPY:%[0-9]+]]:gprb(s32) = COPY [[C]](s32)
    ; LA32-NEXT: PseudoRET
    %0:_(s32) = G_CONSTANT i32 1
    %1:_(s32) = COPY %0(s32)
    PseudoRET

...
---
name:            phys_to_virt
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r4

    ; LA32-LABEL: name: phys_to_virt
    ; LA32: liveins: $r4
    ; LA32-NEXT: {{  $}}
    ; LA32-NEXT: [[COPY:%[0-9]+]]:gprb(s32) = COPY $r4
    ; LA32-NEXT: PseudoRET
    %0:_(s32) = COPY $r4
    PseudoRET

...
