# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc --mtriple=loongarch64 -run-pass=regbankselect \
# RUN:   -simplify-mir -verify-machineinstrs %s \
# RUN:   -o - | FileCheck -check-prefix=LA64 %s

---
name:            virt_to_phys
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:

    ; LA64-LABEL: name: virt_to_phys
    ; LA64: [[C:%[0-9]+]]:gprb(s64) = G_CONSTANT i64 1
    ; LA64-NEXT: $r4 = COPY [[C]](s64)
    ; LA64-NEXT: PseudoRET implicit $r4
    %0:_(s64) = G_CONSTANT i64 1
    $r4 = COPY %0(s64)
    PseudoRET implicit $r4

...
---
name:            phys_to_phys
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r4, $r5

    ; LA64-LABEL: name: phys_to_phys
    ; LA64: liveins: $r4, $r5
    ; LA64-NEXT: {{  $}}
    ; LA64-NEXT: $r4 = COPY $r5
    ; LA64-NEXT: PseudoRET implicit $r4
    $r4 = COPY $r5
    PseudoRET implicit $r4

...
---
name:            virt_to_virt
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:

    ; LA64-LABEL: name: virt_to_virt
    ; LA64: [[C:%[0-9]+]]:gprb(s64) = G_CONSTANT i64 1
    ; LA64-NEXT: [[COPY:%[0-9]+]]:gprb(s64) = COPY [[C]](s64)
    ; LA64-NEXT: PseudoRET
    %0:_(s64) = G_CONSTANT i64 1
    %1:_(s64) = COPY %0(s64)
    PseudoRET

...
---
name:            phys_to_virt
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r4

    ; LA64-LABEL: name: phys_to_virt
    ; LA64: liveins: $r4
    ; LA64-NEXT: {{  $}}
    ; LA64-NEXT: [[COPY:%[0-9]+]]:gprb(s64) = COPY $r4
    ; LA64-NEXT: PseudoRET
    %0:_(s64) = COPY $r4
    PseudoRET

...
