# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc --mtriple=loongarch64 -run-pass=regbankselect \
# RUN:   -simplify-mir -verify-machineinstrs %s \
# RUN:   -o - | FileCheck -check-prefix=LA64 %s

---
name:            load_i8
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $r4

    ; LA64-LABEL: name: load_i8
    ; LA64: liveins: $r4
    ; LA64-NEXT: {{  $}}
    ; LA64-NEXT: [[COPY:%[0-9]+]]:gprb(p0) = COPY $r4
    ; LA64-NEXT: [[LOAD:%[0-9]+]]:gprb(s64) = G_LOAD [[COPY]](p0) :: (load (s8))
    ; LA64-NEXT: $r4 = COPY [[LOAD]](s64)
    ; LA64-NEXT: PseudoRET implicit $r4
    %0:_(p0) = COPY $r4
    %2:_(s64) = G_LOAD %0(p0) :: (load (s8))
    $r4 = COPY %2(s64)
    PseudoRET implicit $r4

...
---
name:            load_i16
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $r4

    ; LA64-LABEL: name: load_i16
    ; LA64: liveins: $r4
    ; LA64-NEXT: {{  $}}
    ; LA64-NEXT: [[COPY:%[0-9]+]]:gprb(p0) = COPY $r4
    ; LA64-NEXT: [[LOAD:%[0-9]+]]:gprb(s64) = G_LOAD [[COPY]](p0) :: (load (s16))
    ; LA64-NEXT: $r4 = COPY [[LOAD]](s64)
    ; LA64-NEXT: PseudoRET implicit $r4
    %0:_(p0) = COPY $r4
    %2:_(s64) = G_LOAD %0(p0) :: (load (s16))
    $r4 = COPY %2(s64)
    PseudoRET implicit $r4

...
---
name:            load_i32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $r4

    ; LA64-LABEL: name: load_i32
    ; LA64: liveins: $r4
    ; LA64-NEXT: {{  $}}
    ; LA64-NEXT: [[COPY:%[0-9]+]]:gprb(p0) = COPY $r4
    ; LA64-NEXT: [[LOAD:%[0-9]+]]:gprb(s64) = G_LOAD [[COPY]](p0) :: (load (s32))
    ; LA64-NEXT: $r4 = COPY [[LOAD]](s64)
    ; LA64-NEXT: PseudoRET implicit $r4
    %0:_(p0) = COPY $r4
    %2:_(s64) = G_LOAD %0(p0) :: (load (s32))
    $r4 = COPY %2(s64)
    PseudoRET implicit $r4

...
---
name:            load_i64
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $r4

    ; LA64-LABEL: name: load_i64
    ; LA64: liveins: $r4
    ; LA64-NEXT: {{  $}}
    ; LA64-NEXT: [[COPY:%[0-9]+]]:gprb(p0) = COPY $r4
    ; LA64-NEXT: [[LOAD:%[0-9]+]]:gprb(s64) = G_LOAD [[COPY]](p0) :: (load (s64))
    ; LA64-NEXT: $r4 = COPY [[LOAD]](s64)
    ; LA64-NEXT: PseudoRET implicit $r4
    %0:_(p0) = COPY $r4
    %1:_(s64) = G_LOAD %0(p0) :: (load (s64))
    $r4 = COPY %1(s64)
    PseudoRET implicit $r4

...
---
name:            load_ptr
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $r4

    ; LA64-LABEL: name: load_ptr
    ; LA64: liveins: $r4
    ; LA64-NEXT: {{  $}}
    ; LA64-NEXT: [[COPY:%[0-9]+]]:gprb(p0) = COPY $r4
    ; LA64-NEXT: [[LOAD:%[0-9]+]]:gprb(p0) = G_LOAD [[COPY]](p0) :: (load (p0))
    ; LA64-NEXT: $r4 = COPY [[LOAD]](p0)
    ; LA64-NEXT: PseudoRET implicit $r4
    %0:_(p0) = COPY $r4
    %1:_(p0) = G_LOAD %0(p0) :: (load (p0))
    $r4 = COPY %1(p0)
    PseudoRET implicit $r4

...
---
name:            zextload_i8
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $r4

    ; LA64-LABEL: name: zextload_i8
    ; LA64: liveins: $r4
    ; LA64-NEXT: {{  $}}
    ; LA64-NEXT: [[COPY:%[0-9]+]]:gprb(p0) = COPY $r4
    ; LA64-NEXT: [[ZEXTLOAD:%[0-9]+]]:gprb(s64) = G_ZEXTLOAD [[COPY]](p0) :: (load (s8))
    ; LA64-NEXT: $r4 = COPY [[ZEXTLOAD]](s64)
    ; LA64-NEXT: PseudoRET implicit $r4
    %0:_(p0) = COPY $r4
    %3:_(s64) = G_ZEXTLOAD %0(p0) :: (load (s8))
    $r4 = COPY %3(s64)
    PseudoRET implicit $r4

...
---
name:            zextload_i16
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $r4

    ; LA64-LABEL: name: zextload_i16
    ; LA64: liveins: $r4
    ; LA64-NEXT: {{  $}}
    ; LA64-NEXT: [[COPY:%[0-9]+]]:gprb(p0) = COPY $r4
    ; LA64-NEXT: [[ZEXTLOAD:%[0-9]+]]:gprb(s64) = G_ZEXTLOAD [[COPY]](p0) :: (load (s16))
    ; LA64-NEXT: $r4 = COPY [[ZEXTLOAD]](s64)
    ; LA64-NEXT: PseudoRET implicit $r4
    %0:_(p0) = COPY $r4
    %3:_(s64) = G_ZEXTLOAD %0(p0) :: (load (s16))
    $r4 = COPY %3(s64)
    PseudoRET implicit $r4

...
---
name:            zextload_i32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $r4

    ; LA64-LABEL: name: zextload_i32
    ; LA64: liveins: $r4
    ; LA64-NEXT: {{  $}}
    ; LA64-NEXT: [[COPY:%[0-9]+]]:gprb(p0) = COPY $r4
    ; LA64-NEXT: [[ZEXTLOAD:%[0-9]+]]:gprb(s64) = G_ZEXTLOAD [[COPY]](p0) :: (load (s32))
    ; LA64-NEXT: $r4 = COPY [[ZEXTLOAD]](s64)
    ; LA64-NEXT: PseudoRET implicit $r4
    %0:_(p0) = COPY $r4
    %1:_(s64) = G_ZEXTLOAD %0(p0) :: (load (s32))
    $r4 = COPY %1(s64)
    PseudoRET implicit $r4

...
---
name:            sextload_i8
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $r4

    ; LA64-LABEL: name: sextload_i8
    ; LA64: liveins: $r4
    ; LA64-NEXT: {{  $}}
    ; LA64-NEXT: [[COPY:%[0-9]+]]:gprb(p0) = COPY $r4
    ; LA64-NEXT: [[SEXTLOAD:%[0-9]+]]:gprb(s64) = G_SEXTLOAD [[COPY]](p0) :: (load (s8))
    ; LA64-NEXT: $r4 = COPY [[SEXTLOAD]](s64)
    ; LA64-NEXT: PseudoRET implicit $r4
    %0:_(p0) = COPY $r4
    %3:_(s64) = G_SEXTLOAD %0(p0) :: (load (s8))
    $r4 = COPY %3(s64)
    PseudoRET implicit $r4

...
---
name:            sextload_i16
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $r4

    ; LA64-LABEL: name: sextload_i16
    ; LA64: liveins: $r4
    ; LA64-NEXT: {{  $}}
    ; LA64-NEXT: [[COPY:%[0-9]+]]:gprb(p0) = COPY $r4
    ; LA64-NEXT: [[SEXTLOAD:%[0-9]+]]:gprb(s64) = G_SEXTLOAD [[COPY]](p0) :: (load (s16))
    ; LA64-NEXT: $r4 = COPY [[SEXTLOAD]](s64)
    ; LA64-NEXT: PseudoRET implicit $r4
    %0:_(p0) = COPY $r4
    %3:_(s64) = G_SEXTLOAD %0(p0) :: (load (s16))
    $r4 = COPY %3(s64)
    PseudoRET implicit $r4

...
---
name:            sextload_i32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $r4

    ; LA64-LABEL: name: sextload_i32
    ; LA64: liveins: $r4
    ; LA64-NEXT: {{  $}}
    ; LA64-NEXT: [[COPY:%[0-9]+]]:gprb(p0) = COPY $r4
    ; LA64-NEXT: [[SEXTLOAD:%[0-9]+]]:gprb(s64) = G_SEXTLOAD [[COPY]](p0) :: (load (s32))
    ; LA64-NEXT: $r4 = COPY [[SEXTLOAD]](s64)
    ; LA64-NEXT: PseudoRET implicit $r4
    %0:_(p0) = COPY $r4
    %1:_(s64) = G_SEXTLOAD %0(p0) :: (load (s32))
    $r4 = COPY %1(s64)
    PseudoRET implicit $r4

...
