# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc --mtriple=loongarch64 -run-pass=regbankselect \
# RUN:   -simplify-mir -verify-machineinstrs %s \
# RUN:   -o - | FileCheck -check-prefix=LA64 %s

---
name:            phi_i64
legalized:       true
tracksRegLiveness: true
body:             |
  ; LA64-LABEL: name: phi_i64
  ; LA64: bb.0:
  ; LA64-NEXT:   liveins: $r4, $r5, $r6
  ; LA64-NEXT: {{  $}}
  ; LA64-NEXT:   [[COPY:%[0-9]+]]:gprb(s64) = COPY $r4
  ; LA64-NEXT:   [[COPY1:%[0-9]+]]:gprb(s64) = COPY $r5
  ; LA64-NEXT:   [[COPY2:%[0-9]+]]:gprb(s64) = COPY $r6
  ; LA64-NEXT:   [[C:%[0-9]+]]:gprb(s64) = G_CONSTANT i64 1
  ; LA64-NEXT:   [[AND:%[0-9]+]]:gprb(s64) = G_AND [[COPY]], [[C]]
  ; LA64-NEXT:   G_BRCOND [[AND]](s64), %bb.2
  ; LA64-NEXT:   G_BR %bb.1
  ; LA64-NEXT: {{  $}}
  ; LA64-NEXT: bb.1:
  ; LA64-NEXT: {{  $}}
  ; LA64-NEXT: bb.2:
  ; LA64-NEXT:   [[PHI:%[0-9]+]]:gprb(s64) = G_PHI [[COPY2]](s64), %bb.1, [[COPY1]](s64), %bb.0
  ; LA64-NEXT:   $r4 = COPY [[PHI]](s64)
  ; LA64-NEXT:   PseudoRET implicit $r4
  bb.0:
    liveins: $r4, $r5, $r6

    %3:_(s64) = COPY $r4
    %1:_(s64) = COPY $r5
    %2:_(s64) = COPY $r6
    %6:_(s64) = G_CONSTANT i64 1
    %5:_(s64) = G_AND %3, %6
    G_BRCOND %5(s64), %bb.2
    G_BR %bb.1

  bb.1:

  bb.2:
    %4:_(s64) = G_PHI %2(s64), %bb.1, %1(s64), %bb.0
    $r4 = COPY %4(s64)
    PseudoRET implicit $r4

...
---
name:            phi_ptr
legalized:       true
tracksRegLiveness: true
body:             |
  ; LA64-LABEL: name: phi_ptr
  ; LA64: bb.0:
  ; LA64-NEXT:   liveins: $r4, $r5, $r6
  ; LA64-NEXT: {{  $}}
  ; LA64-NEXT:   [[COPY:%[0-9]+]]:gprb(s64) = COPY $r4
  ; LA64-NEXT:   [[COPY1:%[0-9]+]]:gprb(p0) = COPY $r5
  ; LA64-NEXT:   [[COPY2:%[0-9]+]]:gprb(p0) = COPY $r6
  ; LA64-NEXT:   [[C:%[0-9]+]]:gprb(s64) = G_CONSTANT i64 1
  ; LA64-NEXT:   [[AND:%[0-9]+]]:gprb(s64) = G_AND [[COPY]], [[C]]
  ; LA64-NEXT:   G_BRCOND [[AND]](s64), %bb.2
  ; LA64-NEXT:   G_BR %bb.1
  ; LA64-NEXT: {{  $}}
  ; LA64-NEXT: bb.1:
  ; LA64-NEXT: {{  $}}
  ; LA64-NEXT: bb.2:
  ; LA64-NEXT:   [[PHI:%[0-9]+]]:gprb(p0) = G_PHI [[COPY2]](p0), %bb.1, [[COPY1]](p0), %bb.0
  ; LA64-NEXT:   $r4 = COPY [[PHI]](p0)
  ; LA64-NEXT:   PseudoRET implicit $r4
  bb.0:
    liveins: $r4, $r5, $r6

    %3:_(s64) = COPY $r4
    %1:_(p0) = COPY $r5
    %2:_(p0) = COPY $r6
    %6:_(s64) = G_CONSTANT i64 1
    %5:_(s64) = G_AND %3, %6
    G_BRCOND %5(s64), %bb.2
    G_BR %bb.1

  bb.1:

  bb.2:
    %4:_(p0) = G_PHI %2(p0), %bb.1, %1(p0), %bb.0
    $r4 = COPY %4(p0)
    PseudoRET implicit $r4

...
