# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc --mtriple=loongarch32 -run-pass=regbankselect \
# RUN:   -simplify-mir -verify-machineinstrs %s \
# RUN:   -o - | FileCheck -check-prefix=LA32 %s

---
name:            phi_i32
legalized:       true
tracksRegLiveness: true
body:             |
  ; LA32-LABEL: name: phi_i32
  ; LA32: bb.0:
  ; LA32-NEXT:   liveins: $r4, $r5, $r6
  ; LA32-NEXT: {{  $}}
  ; LA32-NEXT:   [[COPY:%[0-9]+]]:gprb(s32) = COPY $r4
  ; LA32-NEXT:   [[COPY1:%[0-9]+]]:gprb(s32) = COPY $r5
  ; LA32-NEXT:   [[COPY2:%[0-9]+]]:gprb(s32) = COPY $r6
  ; LA32-NEXT:   [[C:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 1
  ; LA32-NEXT:   [[AND:%[0-9]+]]:gprb(s32) = G_AND [[COPY]], [[C]]
  ; LA32-NEXT:   G_BRCOND [[AND]](s32), %bb.2
  ; LA32-NEXT:   G_BR %bb.1
  ; LA32-NEXT: {{  $}}
  ; LA32-NEXT: bb.1:
  ; LA32-NEXT: {{  $}}
  ; LA32-NEXT: bb.2:
  ; LA32-NEXT:   [[PHI:%[0-9]+]]:gprb(s32) = G_PHI [[COPY2]](s32), %bb.1, [[COPY1]](s32), %bb.0
  ; LA32-NEXT:   $r4 = COPY [[PHI]](s32)
  ; LA32-NEXT:   PseudoRET implicit $r4
  bb.0:
    liveins: $r4, $r5, $r6

    %3:_(s32) = COPY $r4
    %1:_(s32) = COPY $r5
    %2:_(s32) = COPY $r6
    %6:_(s32) = G_CONSTANT i32 1
    %5:_(s32) = G_AND %3, %6
    G_BRCOND %5(s32), %bb.2
    G_BR %bb.1

  bb.1:

  bb.2:
    %4:_(s32) = G_PHI %2(s32), %bb.1, %1(s32), %bb.0
    $r4 = COPY %4(s32)
    PseudoRET implicit $r4

...
---
name:            phi_ptr
legalized:       true
tracksRegLiveness: true
body:             |
  ; LA32-LABEL: name: phi_ptr
  ; LA32: bb.0.entry:
  ; LA32-NEXT:   liveins: $r4, $r5, $r6
  ; LA32-NEXT: {{  $}}
  ; LA32-NEXT:   [[COPY:%[0-9]+]]:gprb(s32) = COPY $r4
  ; LA32-NEXT:   [[COPY1:%[0-9]+]]:gprb(p0) = COPY $r5
  ; LA32-NEXT:   [[COPY2:%[0-9]+]]:gprb(p0) = COPY $r6
  ; LA32-NEXT:   [[C:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 1
  ; LA32-NEXT:   [[AND:%[0-9]+]]:gprb(s32) = G_AND [[COPY]], [[C]]
  ; LA32-NEXT:   G_BRCOND [[AND]](s32), %bb.2
  ; LA32-NEXT:   G_BR %bb.1
  ; LA32-NEXT: {{  $}}
  ; LA32-NEXT: bb.1:
  ; LA32-NEXT: {{  $}}
  ; LA32-NEXT: bb.2:
  ; LA32-NEXT:   [[PHI:%[0-9]+]]:gprb(p0) = G_PHI [[COPY2]](p0), %bb.1, [[COPY1]](p0), %bb.0
  ; LA32-NEXT:   $r4 = COPY [[PHI]](p0)
  ; LA32-NEXT:   PseudoRET implicit $r4
  bb.0.entry:
    liveins: $r4, $r5, $r6

    %3:_(s32) = COPY $r4
    %1:_(p0) = COPY $r5
    %2:_(p0) = COPY $r6
    %6:_(s32) = G_CONSTANT i32 1
    %5:_(s32) = G_AND %3, %6
    G_BRCOND %5(s32), %bb.2
    G_BR %bb.1

  bb.1:

  bb.2:
    %4:_(p0) = G_PHI %2(p0), %bb.1, %1(p0), %bb.0
    $r4 = COPY %4(p0)
    PseudoRET implicit $r4

...
