# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc --mtriple=loongarch64 -run-pass=regbankselect \
# RUN:   -simplify-mir -verify-machineinstrs %s \
# RUN:   -o - | FileCheck -check-prefix=LA64 %s

---
name:            select_i64
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r4, $r5, $r6

    ; LA64-LABEL: name: select_i64
    ; LA64: liveins: $r4, $r5, $r6
    ; LA64-NEXT: {{  $}}
    ; LA64-NEXT: [[COPY:%[0-9]+]]:gprb(s64) = COPY $r4
    ; LA64-NEXT: [[COPY1:%[0-9]+]]:gprb(s64) = COPY $r5
    ; LA64-NEXT: [[COPY2:%[0-9]+]]:gprb(s64) = COPY $r6
    ; LA64-NEXT: [[C:%[0-9]+]]:gprb(s64) = G_CONSTANT i64 1
    ; LA64-NEXT: [[AND:%[0-9]+]]:gprb(s64) = G_AND [[COPY]], [[C]]
    ; LA64-NEXT: [[SELECT:%[0-9]+]]:gprb(s64) = G_SELECT [[AND]](s64), [[COPY1]], [[COPY2]]
    ; LA64-NEXT: $r4 = COPY [[SELECT]](s64)
    ; LA64-NEXT: PseudoRET implicit $r4
    %3:_(s64) = COPY $r4
    %4:_(s64) = COPY $r5
    %5:_(s64) = COPY $r6
    %12:_(s64) = G_CONSTANT i64 1
    %11:_(s64) = G_AND %3, %12
    %10:_(s64) = G_SELECT %11(s64), %4, %5
    $r4 = COPY %10(s64)
    PseudoRET implicit $r4

...
---
name:            select_ptr
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r4, $r5, $r6

    ; LA64-LABEL: name: select_ptr
    ; LA64: liveins: $r4, $r5, $r6
    ; LA64-NEXT: {{  $}}
    ; LA64-NEXT: [[COPY:%[0-9]+]]:gprb(s64) = COPY $r4
    ; LA64-NEXT: [[COPY1:%[0-9]+]]:gprb(p0) = COPY $r5
    ; LA64-NEXT: [[COPY2:%[0-9]+]]:gprb(p0) = COPY $r6
    ; LA64-NEXT: [[C:%[0-9]+]]:gprb(s64) = G_CONSTANT i64 1
    ; LA64-NEXT: [[AND:%[0-9]+]]:gprb(s64) = G_AND [[COPY]], [[C]]
    ; LA64-NEXT: [[SELECT:%[0-9]+]]:gprb(p0) = G_SELECT [[AND]](s64), [[COPY1]], [[COPY2]]
    ; LA64-NEXT: $r4 = COPY [[SELECT]](p0)
    ; LA64-NEXT: PseudoRET implicit $r4
    %3:_(s64) = COPY $r4
    %4:_(p0) = COPY $r5
    %5:_(p0) = COPY $r6
    %12:_(s64) = G_CONSTANT i64 1
    %11:_(s64) = G_AND %3, %12
    %10:_(p0) = G_SELECT %11(s64), %4, %5
    $r4 = COPY %10(p0)
    PseudoRET implicit $r4

...
