# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc --mtriple=loongarch32 -run-pass=regbankselect \
# RUN:   -simplify-mir -verify-machineinstrs %s \
# RUN:   -o - | FileCheck -check-prefix=LA32 %s

---
name:            select_i32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r4, $r5, $r6

    ; LA32-LABEL: name: select_i32
    ; LA32: liveins: $r4, $r5, $r6
    ; LA32-NEXT: {{  $}}
    ; LA32-NEXT: [[COPY:%[0-9]+]]:gprb(s32) = COPY $r4
    ; LA32-NEXT: [[COPY1:%[0-9]+]]:gprb(s32) = COPY $r5
    ; LA32-NEXT: [[COPY2:%[0-9]+]]:gprb(s32) = COPY $r6
    ; LA32-NEXT: [[C:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 1
    ; LA32-NEXT: [[AND:%[0-9]+]]:gprb(s32) = G_AND [[COPY]], [[C]]
    ; LA32-NEXT: [[SELECT:%[0-9]+]]:gprb(s32) = G_SELECT [[AND]](s32), [[COPY1]], [[COPY2]]
    ; LA32-NEXT: $r4 = COPY [[SELECT]](s32)
    ; LA32-NEXT: PseudoRET implicit $r4
    %3:_(s32) = COPY $r4
    %4:_(s32) = COPY $r5
    %5:_(s32) = COPY $r6
    %12:_(s32) = G_CONSTANT i32 1
    %11:_(s32) = G_AND %3, %12
    %10:_(s32) = G_SELECT %11(s32), %4, %5
    $r4 = COPY %10(s32)
    PseudoRET implicit $r4

...
---
name:            select_ptr
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r4, $r5, $r6

    ; LA32-LABEL: name: select_ptr
    ; LA32: liveins: $r4, $r5, $r6
    ; LA32-NEXT: {{  $}}
    ; LA32-NEXT: [[COPY:%[0-9]+]]:gprb(s32) = COPY $r4
    ; LA32-NEXT: [[COPY1:%[0-9]+]]:gprb(p0) = COPY $r5
    ; LA32-NEXT: [[COPY2:%[0-9]+]]:gprb(p0) = COPY $r6
    ; LA32-NEXT: [[C:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 1
    ; LA32-NEXT: [[AND:%[0-9]+]]:gprb(s32) = G_AND [[COPY]], [[C]]
    ; LA32-NEXT: [[SELECT:%[0-9]+]]:gprb(p0) = G_SELECT [[AND]](s32), [[COPY1]], [[COPY2]]
    ; LA32-NEXT: $r4 = COPY [[SELECT]](p0)
    ; LA32-NEXT: PseudoRET implicit $r4
    %3:_(s32) = COPY $r4
    %4:_(p0) = COPY $r5
    %5:_(p0) = COPY $r6
    %12:_(s32) = G_CONSTANT i32 1
    %11:_(s32) = G_AND %3, %12
    %10:_(p0) = G_SELECT %11(s32), %4, %5
    $r4 = COPY %10(p0)
    PseudoRET implicit $r4

...
