# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc --mtriple=loongarch32 -run-pass=regbankselect \
# RUN:   -simplify-mir -verify-machineinstrs %s \
# RUN:   -o - | FileCheck -check-prefix=LA32 %s

---
name:            store_i8
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $r4, $r5

    ; LA32-LABEL: name: store_i8
    ; LA32: liveins: $r4, $r5
    ; LA32-NEXT: {{  $}}
    ; LA32-NEXT: [[COPY:%[0-9]+]]:gprb(s32) = COPY $r4
    ; LA32-NEXT: [[COPY1:%[0-9]+]]:gprb(p0) = COPY $r5
    ; LA32-NEXT: G_STORE [[COPY]](s32), [[COPY1]](p0) :: (store (s8))
    ; LA32-NEXT: PseudoRET
    %2:_(s32) = COPY $r4
    %1:_(p0) = COPY $r5
    G_STORE %2(s32), %1(p0) :: (store (s8))
    PseudoRET

...
---
name:            store_i16
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $r4, $r5

    ; LA32-LABEL: name: store_i16
    ; LA32: liveins: $r4, $r5
    ; LA32-NEXT: {{  $}}
    ; LA32-NEXT: [[COPY:%[0-9]+]]:gprb(s32) = COPY $r4
    ; LA32-NEXT: [[COPY1:%[0-9]+]]:gprb(p0) = COPY $r5
    ; LA32-NEXT: G_STORE [[COPY]](s32), [[COPY1]](p0) :: (store (s16))
    ; LA32-NEXT: PseudoRET
    %2:_(s32) = COPY $r4
    %1:_(p0) = COPY $r5
    G_STORE %2(s32), %1(p0) :: (store (s16))
    PseudoRET

...
---
name:            store_i32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $r4, $r5

    ; LA32-LABEL: name: store_i32
    ; LA32: liveins: $r4, $r5
    ; LA32-NEXT: {{  $}}
    ; LA32-NEXT: [[COPY:%[0-9]+]]:gprb(s32) = COPY $r4
    ; LA32-NEXT: [[COPY1:%[0-9]+]]:gprb(p0) = COPY $r5
    ; LA32-NEXT: G_STORE [[COPY]](s32), [[COPY1]](p0) :: (store (s32))
    ; LA32-NEXT: PseudoRET
    %0:_(s32) = COPY $r4
    %1:_(p0) = COPY $r5
    G_STORE %0(s32), %1(p0) :: (store (s32))
    PseudoRET

...
---
name:            store_ptr
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $r4, $r5

    ; LA32-LABEL: name: store_ptr
    ; LA32: liveins: $r4, $r5
    ; LA32-NEXT: {{  $}}
    ; LA32-NEXT: [[COPY:%[0-9]+]]:gprb(p0) = COPY $r4
    ; LA32-NEXT: [[COPY1:%[0-9]+]]:gprb(p0) = COPY $r5
    ; LA32-NEXT: G_STORE [[COPY]](p0), [[COPY1]](p0) :: (store (p0), align 8)
    ; LA32-NEXT: PseudoRET
    %0:_(p0) = COPY $r4
    %1:_(p0) = COPY $r5
    G_STORE %0(p0), %1(p0) :: (store (p0), align 8)
    PseudoRET

...
