# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc --mtriple=loongarch64 -run-pass=regbankselect \
# RUN:   -simplify-mir -verify-machineinstrs %s \
# RUN:   -o - | FileCheck -check-prefix=LA64 %s

---
name:            store_i8
legalized:       true
body:             |
  bb.0:
    liveins: $r4, $r5

    ; LA64-LABEL: name: store_i8
    ; LA64: liveins: $r4, $r5
    ; LA64-NEXT: {{  $}}
    ; LA64-NEXT: [[COPY:%[0-9]+]]:gprb(s64) = COPY $r4
    ; LA64-NEXT: [[COPY1:%[0-9]+]]:gprb(p0) = COPY $r5
    ; LA64-NEXT: G_STORE [[COPY]](s64), [[COPY1]](p0) :: (store (s8))
    ; LA64-NEXT: PseudoRET
    %2:_(s64) = COPY $r4
    %1:_(p0) = COPY $r5
    G_STORE %2(s64), %1(p0) :: (store (s8))
    PseudoRET

...
---
name:            store_i16
legalized:       true
body:             |
  bb.0:
    liveins: $r4, $r5

    ; LA64-LABEL: name: store_i16
    ; LA64: liveins: $r4, $r5
    ; LA64-NEXT: {{  $}}
    ; LA64-NEXT: [[COPY:%[0-9]+]]:gprb(s64) = COPY $r4
    ; LA64-NEXT: [[COPY1:%[0-9]+]]:gprb(p0) = COPY $r5
    ; LA64-NEXT: G_STORE [[COPY]](s64), [[COPY1]](p0) :: (store (s16))
    ; LA64-NEXT: PseudoRET
    %2:_(s64) = COPY $r4
    %1:_(p0) = COPY $r5
    G_STORE %2(s64), %1(p0) :: (store (s16))
    PseudoRET

...
---
name:            store_i32
legalized:       true
body:             |
  bb.0:
    liveins: $r4, $r5

    ; LA64-LABEL: name: store_i32
    ; LA64: liveins: $r4, $r5
    ; LA64-NEXT: {{  $}}
    ; LA64-NEXT: [[COPY:%[0-9]+]]:gprb(s64) = COPY $r4
    ; LA64-NEXT: [[COPY1:%[0-9]+]]:gprb(p0) = COPY $r5
    ; LA64-NEXT: G_STORE [[COPY]](s64), [[COPY1]](p0) :: (store (s32))
    ; LA64-NEXT: PseudoRET
    %2:_(s64) = COPY $r4
    %1:_(p0) = COPY $r5
    G_STORE %2(s64), %1(p0) :: (store (s32))
    PseudoRET

...
---
name:            store_i64
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $r4, $r5

    ; LA64-LABEL: name: store_i64
    ; LA64: liveins: $r4, $r5
    ; LA64-NEXT: {{  $}}
    ; LA64-NEXT: [[COPY:%[0-9]+]]:gprb(s64) = COPY $r4
    ; LA64-NEXT: [[COPY1:%[0-9]+]]:gprb(p0) = COPY $r5
    ; LA64-NEXT: G_STORE [[COPY]](s64), [[COPY1]](p0) :: (store (s64))
    ; LA64-NEXT: PseudoRET
    %0:_(s64) = COPY $r4
    %1:_(p0) = COPY $r5
    G_STORE %0(s64), %1(p0) :: (store (s64))
    PseudoRET

...
---
name:            store_ptr
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $r4, $r5

    ; LA64-LABEL: name: store_ptr
    ; LA64: liveins: $r4, $r5
    ; LA64-NEXT: {{  $}}
    ; LA64-NEXT: [[COPY:%[0-9]+]]:gprb(p0) = COPY $r4
    ; LA64-NEXT: [[COPY1:%[0-9]+]]:gprb(p0) = COPY $r5
    ; LA64-NEXT: G_STORE [[COPY]](p0), [[COPY1]](p0) :: (store (p0))
    ; LA64-NEXT: PseudoRET
    %0:_(p0) = COPY $r4
    %1:_(p0) = COPY $r5
    G_STORE %0(p0), %1(p0) :: (store (p0))
    PseudoRET

...
